### ISSUE TITLE
Kafka not working after upgrading to Hoxton.SR9

### ISSUE THREAD

**Issue by aariza1** [spring-cloud/spring-cloud-stream-binder-kafka#1021]
Hello,
I have been getting the following exception in all our services that include Kafka after upgrading to Hoxton.SR9.
With Hoxton.SR8 is working just fine.

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException:

Somehow the service is not able to subscribe to the kafka topic.

We are also using Spring Boot 2.3.6.RELEASE
Any idea what could be triggering this error?
I posted an issue on the spring-kafka project and i was told to post it here.

This is the stacktrace
```
org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}], failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}]
at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:157)
at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:113)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:2037)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1936)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1863)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1757)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1478)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1141)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1044)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}], failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}]
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2052)
... 10 common frames omitted
Caused by: org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}]
at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:390)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:77)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:449)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:423)
at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120)
at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211)
at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:114)
at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:40)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2004)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1986)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1923)
... 8 common frames omitted
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139)
at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
... 27 common frames omitted`
```
Thank you in advance!

**Comment by garyrussell** [comment]
Sorry for tthe delay. I am not familiar with Kotlin Gradle scripts; I am getting

>Plugin [id: 'org.jetbrains.kotlin.jvm'] was not found in any of the following sources:

when loading your project into IntelliJ IDEA.

**Comment by garyrussell** [comment]
I got around that by adding `version "1.4.30"` to those 3 entries.

Now I am getting `Could not resolve de.otto.prada.common:util-spring-boot-starter:2.0.0.` ... `Amazon S3; Status Code: 403; Error Code: AccessDenied; `

Could you please strip this down to the bare minimum to reproduce the behavior you see without all these extra dependencies?

**Comment by aariza1** [comment]
Hello Gary, there is no need now. We have upgraded to Hoxton.SR10 and everything works perfectly. 
Thank you very much
