### ISSUE TITLE
.branch() with Kotlin Array<KStream<..>> fail with 'Attempted to reify generic array type'

### ISSUE THREAD

**Issue by hartmut-co-uk** [spring-cloud/spring-cloud-stream-binder-kafka#1044]
Hi, I've tried to port a first example from Java to Kotlin, code compiles fine but fails at runtime with
`Caused by: java.lang.UnsupportedOperationException: Attempted to reify generic array type, whose generic component type could not be reified to some Class<?>. Handling for this case is not implemented`

Is there any known working example?
Does it need to be defined as an `inline` fun + `reified` maybe - if so, which part? 
The `KStream<K, V>` inside `Array<>`?

Working **Java** equivalent:
```java
public Function<KStream<Object, String>, KStream<?, WordCount>[]> process() {
```
_Source: https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/kafka-streams-samples/kafka-streams-branching/src/main/java/kafka/streams/branching/KafkaStreamsBranchingSample.java_

~ported to **Kotlin**:
```kotlin
@Configuration
class KafkaStreamsTopologies {

    val isEnglish = Predicate<Any, WordCount> { _, v -> v.word == "english" }
    val isFrench = Predicate<Any, WordCount> { _, v -> v.word == "french" }
    val isSpanish = Predicate<Any, WordCount> { _, v -> v.word == "spanish" }

    @Bean
    //fun process() = Function<KStream<String?, String?>, Array<KStream<String?, WordCount?>>> { input ->
    fun process(): Function<KStream<String?, String?>, Array<KStream<String?, WordCount?>>> = Function { input ->
        input
            .flatMapValues { value -> value?.toLowerCase()?.split("\\W+")?.toList() }
            .groupBy { _, value -> value }
            .windowedBy(TimeWindows.of(Duration.ofSeconds(6)))
            .count(Materialized.`as`("WordCounts-1"))
            .toStream()
            .map { key, value -> KeyValue.pair<String?, WordCount?>(null,
                    WordCount(key.key(), value, Date(key.window().start()), Date(key.window().end()))) }
            .branch(isEnglish, isFrench, isSpanish)
    }

}

data class WordCount(var word: String, var count: Long, var start: Date, var end: Date)
```

**Error message (runtime, app startup)**
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionBindingRegistrar' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.UnsupportedOperationException: Attempted to reify generic array type, whose generic component type could not be reified to some Class<?>. Handling for this case is not implemented
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.3.jar:2.4.3]
	at com.example.springcloudkafkastreamsmultifkjoin.SpringCloudKafkaStreamsMultiFkjoinApplicationKt.main(SpringCloudKafkaStreamsMultiFkjoinApplication.kt:92) ~[main/:na]
Caused by: java.lang.UnsupportedOperationException: Attempted to reify generic array type, whose generic component type could not be reified to some Class<?>. Handling for this case is not implemented
	at net.jodah.typetools.TypeResolver.reify(TypeResolver.java:449) ~[typetools-0.6.2.jar:0.6.2]
	at net.jodah.typetools.TypeResolver.reify(TypeResolver.java:430) ~[typetools-0.6.2.jar:0.6.2]
	at net.jodah.typetools.TypeResolver.reify(TypeResolver.java:402) ~[typetools-0.6.2.jar:0.6.2]
	at net.jodah.typetools.TypeResolver.reify(TypeResolver.java:205) ~[typetools-0.6.2.jar:0.6.2]
	at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionTypeFromClass(FunctionTypeUtils.java:152) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
	at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionType(FunctionTypeUtils.java:260) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:139) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
	at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:42) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionBindingRegistrar.determineFunctionName(FunctionConfiguration.java:880) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionBindingRegistrar.afterPropertiesSet(FunctionConfiguration.java:778) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.4.jar:5.3.4]
	... 17 common frames omitted

```

**Comment by sobychacko** [comment]
@hartmut-co-uk Do you only see this error when using the Array types? Any chance you can put this in a repo where we can debug this further?

**Comment by hartmut-co-uk** [comment]
Thanks @sobychacko - yes only for Array<> type, all fine for other functional interface defined kafka stream topologies.
I will provide a repo tomorrow.

**Comment by hartmut-co-uk** [comment]
https://github.com/hartmut-co-uk/spring-cloud-stream-binder-kafka-issue-1044

**Comment by sobychacko** [comment]
@hartmut-co-uk There was an issue with the way `KStream[]` types are found and scanned in Spring Cloud Function. We just fixed it, see this commit: https://github.com/spring-cloud/spring-cloud-function/commit/6401697f18976ece0d43a6fea46b721ec68a551e.

Could you try this with the latest `3.1.x` snapshot (`3.1.3-SNAPSHOT`)?

**Comment by hartmut-co-uk** [comment]
👌 Many thanks, will do and give feedback.

**Comment by sobychacko** [comment]
@hartmut-co-uk Any updates on testing this?

**Comment by hartmut-co-uk** [comment]
Verified working!
https://github.com/hartmut-co-uk/spring-cloud-stream-binder-kafka-issue-1044/commit/440c6903f336110d8a79369ee163354700142ce6

Apologies for the delay and thanks again for the quick analysis & fix!
