### ISSUE TITLE
kafka consumer attempts to acquire info from a partition that is no longer assigned to it

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream-binder-kafka#1090]
-  spring-cloud-stream-binder-kafka 3.0.9-RELEASE
-  spring-boot 2.2.13.RELEASE

Hi, we have a project using Spring Cloud Stream with kafka and we are having a problem in reconnecting the consumers when the broker nodes are down in a cluster for a period of time.

The problem is that the consumer is not able to reconnect and acquire the partitions because it is trying to check the offset position of a partition that is no longer assigned to it: Error while processing: nulljava.lang.IllegalStateException: You can only check the position for partitions assigned to this consumer.

The logs are shown below:
```
2021-06-09T09:39:25.358Z [appscs-45-6gvd4] [WARN] [KafkaConsumerDestination{consumerDestinationName='topicName1', partitions=0, dlqName='null'}.container-0-C-1] [messageKey=] [Consumer clientId=clientid-0, groupId=groupid-v1] Connection to node 2147483644 (hostnode/10.71.34.4:9092) could not be established. Broker may not be available.

2021-06-09T09:42:30.217Z [appscs-45-6gvd4] [ERROR] [KafkaConsumerDestination{consumerDestinationName='topicName1', partitions=0, dlqName='null'}.container-0-C-1] [messageKey=] [Consumer clientId=clientid-0, groupId=groupid-v1] User provided listener org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ListenerConsumerRebalanceListener failed on invocation of onPartitionsAssigned for partitions [topicName1-1]org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition topicName1-1 could be determined

2021-06-09T09:42:30.217Z [appscs-45-6gvd4] [ERROR] [KafkaConsumerDestination{consumerDestinationName='topicName1', partitions=0, dlqName='null'}.container-0-C-1] [messageKey=] Error while processing: nullorg.apache.kafka.common.KafkaException: User rebalance callback throws an error\\n  at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:403)\\nCaused by: org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition topicName1-1 could be determined"

2021-06-09T09:43:03.924Z [appscs-45-6gvd4] [ERROR] [KafkaConsumerDestination{consumerDestinationName='topicName1', partitions=0, dlqName='null'}.container-0-C-1] [messageKey=] Error while processing: nulljava.lang.IllegalStateException: You can only check the position for partitions assigned to this consumer.\\n   at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1717)
```

Is it possible that the kafka binder stores information about the previously assigned partition and tries to connect to it even though a rebalance has already been performed and it is now assigned to another consumer?

NOTE: The configuration of the consumer Assignor is the default (RangeAssignor).
NOTE 2: The only way to restore the correct state of the application is to perform a redeployment.

**Comment by sobychacko** [comment]
@ferblaca It is not clear how this could happen. Obviously, the container thread is involved and the call to `position` in the container occurs when the partition is assigned. I am curious how that partition gets assigned from the binder. It would be very helpful if you can provide us with some steps to reproduce the issue in order to triage this further. Thanks!

**Comment by sobychacko** [comment]
Closing this due to inactivity. Feel free to open it and provide reproducible steps.
