### ISSUE TITLE
Problem setting the BatchErrorHandler with the ListenerContainerCustomizer

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream-binder-kafka#1140]
We have problems setting up a **BatchErrorHandler** with **ListenerContainerCustomizer** for an application that has Kafka consumers in both Batch and non-Batch mode.

The main problem is that from the Customizer **we are not able to differentiate if the container is configured in Batch mode or not to set the BatchErrorHandler or not**:

```
  @Bean
  public ListenerContainerCustomizer batchListenerContainerCustomizer() {
      return (container, destinationName, group) -> {
          if (container instanceof ConcurrentMessageListenerContainer) {
              final ConcurrentMessageListenerContainer messageListenerContainer = (ConcurrentMessageListenerContainer) container;

              messageListenerContainer.setBatchErrorHandler(new RetryingBatchErrorHandler(new FixedBackOff(500L, 1),
                  null));
          }
      };
  }
```

And if we always set the BatchErrorHandler for all consumers, at a later stage it gives a validation error that we show below:

```
org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:462) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:177) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:134) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:118) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.9.jar:5.3.9]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.4.jar:2.5.4]
	at com.example.stream.kafka.batch.demoKafkaBatch.DemoKafkaBatchApplication.main(DemoKafkaBatchApplication.java:24) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:563) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.IllegalStateException: Error handler is not compatible with the message listener, expecting an instance of ErrorHandler not org.springframework.kafka.listener.RetryingBatchErrorHandler
	at org.springframework.util.Assert.state(Assert.java:97) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.validateErrorHandler(KafkaMessageListenerContainer.java:1135) ~[spring-kafka-2.7.6.jar:2.7.6]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:756) ~[spring-kafka-2.7.6.jar:2.7.6]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer.doStart(KafkaMessageListenerContainer.java:320) ~[spring-kafka-2.7.6.jar:2.7.6]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:397) ~[spring-kafka-2.7.6.jar:2.7.6]
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:205) ~[spring-kafka-2.7.6.jar:2.7.6]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:397) ~[spring-kafka-2.7.6.jar:2.7.6]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.doStart(KafkaMessageDrivenChannelAdapter.java:326) ~[spring-integration-kafka-5.5.3.jar:5.5.3]
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:157) ~[spring-integration-core-5.5.3.jar:5.5.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:415) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	... 29 common frames omitted
```

We see some alternatives as a solution, but the simplest one could be the following:

1. Add as an argument in the `configure` method of the **ListenerContainerCustomizer** the `extendedConsumerProperties` to be able to set the **BatchErrorHandler** depending on the value of  `extendedConsumerProperties.isBatchMode()` at this point: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/main/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L780

Another alternative is in **KafkaMessageListenerContainer** when setting the **BatchErrorHandler** (`ListenerContainer.setBatchErrorHandler()`), store it in another variable different from `errorHandler` (e.g. batchErrorHandler) and when validating in [at this point](https://github.com/spring-projects/spring-kafka/blob/a66106061627c70067be5af25585cf6b57e327c9/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1164), if it is batch mode, check with the new variable...

Attached is a project that reproduces the problem described.
[demoKafkaBatch.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/7129881/demoKafkaBatch.zip)

**Comment by garyrussell** [comment]
You can't use the `AckMode` to detect the listener type (BATCH is valid for a record listener; use the listener itself...
```java
@Bean
public ListenerContainerCustomizer batchListenerContainerCustomizer() {
	return (container, destinationName, group) -> {
		if (container instanceof ConcurrentMessageListenerContainer) {
			final ConcurrentMessageListenerContainer messageListenerContainer = (ConcurrentMessageListenerContainer) container;

			if (messageListenerContainer.getContainerProperties()
					.getMessageListener() instanceof BatchMessageListener) {

				final FixedBackOff fixedBackOff = new FixedBackOff(500L, 1);
				messageListenerContainer.setBatchErrorHandler(new RetryingBatchErrorHandler(fixedBackOff,
						null));
			}
		}
	};
}
```
```
inputRecord:Foo [bar=baz]
inputBatch:Foo [bar=baz]
inputRecord:Foo [bar=qux]
inputBatch:Foo [bar=qux]
```

**Comment by ferblaca** [comment]
Thanks @garyrussell, 

I have added the condition in my sample application but the `messageListener` field in `containerProperties` is always set to null and therefore I never end up setting the BatchErrorHandler to container...

On the other hand, in the [documentation ](https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/current/reference/html/overview.html#_consuming_batches) it indicates that for consumers in batch mode retry is not supported and that by default `maxAttempts` is 1, however, in the example I attach (by not setting the BatchErrorHandler) the retries are infinite. Is this behaviour normal?

Attached is an example that reproduces the problem.
[demoKafkaBatch.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/7133999/demoKafkaBatch.zip)

**Comment by garyrussell** [comment]
Oh, right; sorry, yes; the listener is added later by the channel adapter.

Can you not use the `destinationName, group` to determine which type of error handler you want?

Retry is not supported in the binder, but it can be configured via the error handler (and the default batch error handler will retry indefinitely).

Error handling with batch listeners is difficult and is better handled in the listener itself.

However, newer versions of Spring for Apache Kafka have a new handler `RecoveringBatchErrorHandler` where the application throws a specific exception to indicate which record in the batch failed.

https://docs.spring.io/spring-kafka/docs/current/reference/html/#recovering-batch-eh

**Comment by ferblaca** [comment]
The objective is to create a utility that auto-configures the consumers in batch mode for several applications dynamically, without having to register in the logic the names of the destinations or groups to set the BatchErrorHandler. This is why we propose the two alternatives of the first post ;)

Regarding the `RecoveringBatchErrorHandler` sounds great! I will try it.

On the other hand, I have also been trying to manage the Batch consumption manually (`AckMode.MANUAL`) using the `Acknowledgment` object obtained from the `KafkaHeaders.ACKNOWLEDGMENT` header. But the nack() methods are not supported by the class, and I can't cast the `Acknowledgment` Object to `ConsumerBatchAcknowledgment` either as it is a private class. I mention this because the [documentation ](https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/current/reference/html/overview.html#_consuming_batches) also talks about manually using `nack()` to perform partial acks.

**Comment by garyrussell** [comment]
```yaml
spring:
  cloud:
    function:
      definition: inputBatch;inputRecord
    stream:
      bindings:
        inputBatch-in-0:
          group: foo-bathc-group
          destination: inputBatchTopic
          consumer:
            batch-mode: true
        inputRecord-in-0:
          group: foo-record-group
          destination: inputRecordTopic
          consumer:
            batch-mode: false
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            batch.size: 16384
            linger.ms: 10000

```
```java
@Bean
public ListenerContainerCustomizer batchListenerContainerCustomizer() {
	return (container, destinationName, group) -> {
		if (container instanceof ConcurrentMessageListenerContainer) {
			final ConcurrentMessageListenerContainer messageListenerContainer = (ConcurrentMessageListenerContainer) container;

			if (group.equals("foo-bathc-group")) {

				final FixedBackOff fixedBackOff = new FixedBackOff(500L, 1);
				messageListenerContainer.setBatchErrorHandler(new RetryingBatchErrorHandler(fixedBackOff,
						null));
			}
		}
	};
}
```

**Comment by garyrussell** [comment]
I see; well you could use a convention in the group name, as a work around.

It's not clear what you mean about nack; this works fine for me with your example:

```yaml
spring:
  cloud:
    function:
      definition: inputBatch;inputRecord
    stream:
      bindings:
        inputBatch-in-0:
          group: foo-bathc-group
          destination: inputBatchTopic
          consumer:
            batch-mode: true
        inputRecord-in-0:
          group: foo-record-group
          destination: inputRecordTopic
          consumer:
            batch-mode: false
      kafka:
        bindings:
          inputBatch-in-0:
            consumer:
              ackMode: manual
        binder:
          brokers: localhost:9092
          configuration:
            batch.size: 16384
            linger.ms: 10000
```

```java
@Bean
public Consumer<Message<List<Foo>>> inputBatch() throws Exception {
	return msg -> {
		msg.getPayload().stream()
				.forEach(foo -> System.out.println("inputBatch:" + foo));
		if (msg.getPayload().size() > 1) {
			msg.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class).nack(1, 0L);
		}
		else {
			msg.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class).acknowledge();
		}
	};
}
```
```
inputRecord:Foo [bar=baz]
inputBatch:Foo [bar=baz]
inputBatch:Foo [bar=qux]
inputRecord:Foo [bar=qux]
2021-09-09 11:19:07.328...  Seeking to offset 19 for partition inputBatchTopic-0
inputBatch:Foo [bar=qux]
```
Perhaps you were looking at some other `Acknowledgment` class?

By the way, in the next release, we have deprecated `ErrorHandler/BatchErrorHandler`  in favor of `CommonErrorHandler`.

This was driven by the need to support both types of listener in the same container factory for `@KafkaListener`s.

**Comment by ferblaca** [comment]
Thanks @garyrussell,

Regarding the use of Acknowledgment class, it was my problem, I was using it incorrectly. Thank you.

As a future improvement, it would be great to be able to set the `CommonErrorHandler` from a property of the binding consumer (Maybe be able to set the beanName of a CommonErrorHandler registered by the developer), without having to use the `ListenerContainerCustomizer` and check the destination/group to set an errorHandler to each binding.
