### ISSUE TITLE
Can't convert value of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in value.serializer, failedMessage=GenericMessage

### ISSUE THREAD

**Issue by clay-f** [spring-cloud/spring-cloud-stream-binder-kafka#1154]
I'm used to send byte message is correct but upgrade  2020.0.4 from 2020.0.3 get this error

error
```
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$ProducerConfigurationMessageHandler@2241c365]; nested exception is
org.apache.kafka.common.errors.SerializationException: Can't convert value of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in value.serializer, failedMessage=GenericMessage 
[payload=filmeafadfafdsaaahttps://www.fdasfasd.fasdf,
headers={target-protocol=streamBridge, id=0a7045f1-4c7d-8cca-0e60-74ed1071b472, timestamp=1632657197603}]
at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1056)
at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:215)
at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:156)
at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:136)
at com.f.crawl.spider.filmspier.message.producer.ProcessPlayerAndFilmProducer.addFilterFilmTask(ProcessPlayerAndFilmProducer.java:41)
at com.f.crawl.spider.filmspier.AbstractFilmSpider.processFilmAndDetailBySendBroker(AbstractFilmSpider.java:116)
at com.f.crawl.spider.filmspier.AbstractFilmSpider.processFilmAndPlayerDetailByRequestDetailInfo(AbstractFilmSpider.java:78)
at com.f.crawl.spider.filmspier.AbstractFilmSpider.processFilmAndPlayerDetail(AbstractFilmSpider.java:64)
at com.f.crawl.spider.filmspier.AbstractDocumentFilmSpider.pageStyleCrawl(AbstractDocumentFilmSpider.java:97)
at com.f.crawl.spider.filmspier.HeyzoSpider.execute(HeyzoSpider.java:40)
... 6 more
Caused by: org.apache.kafka.common.errors.SerializationException: Can't convert value of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in value.serializer
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class [B (java.lang.String and [B are in module java.base of loader 'bootstrap')
at org.apache.kafka.common.serialization.ByteArraySerializer.serialize(ByteArraySerializer.java:19)
at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:926)
at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:886)
at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.send(DefaultKafkaProducerFactory.java:864)
at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:580)
at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:406)
at org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.handleRequestMessage(KafkaProducerMessageHandler.java:497)
at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)
at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1056)
at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:215)
at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:156)
at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:136)
at com.f.crawl.spider.filmspier.message.producer.ProcessPlayerAndFilmProducer.addFilterFilmTask(ProcessPlayerAndFilmProducer.java:41)
at com.f.crawl.spider.filmspier.AbstractFilmSpider.processFilmAndDetailBySendBroker(AbstractFilmSpider.java:116)
at com.f.crawl.spider.filmspier.AbstractFilmSpider.processFilmAndPlayerDetailByRequestDetailInfo(AbstractFilmSpider.java:78)
at com.f.crawl.spider.filmspier.AbstractFilmSpider.processFilmAndPlayerDetail(AbstractFilmSpider.java:64)
at com.f.crawl.spider.filmspier.AbstractDocumentFilmSpider.pageStyleCrawl(AbstractDocumentFilmSpider.java:97)
at com.f.crawl.spider.filmspier.HeyzoSpider.execute(HeyzoSpider.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)

```

send message code

```
 FilmAndPlayers.FilmAndPlayer filmAndPlayer = FilmAndPlayers.FilmAndPlayer.newBuilder()
                .setFilm(film)
                .addAllPlayer(players)
                .setHaveSpecialRule((Boolean) params.get("haveProps"))
                .build();
        streamBridge.send("film-task-output-out-0", MessageBuilder.withPayload(filmAndPlayer.toByteArray()).build());
```

application.yml
```
spring:
  application:
    name: film
  main:
    banner-mode: "off"
  cloud:
    stream:
      bindings:
        film-task-output-out-0:
          destination: film-task-topic
          producer:
            useNativeEncoding: true
        film-in:
          destination: film-task-topic
          group: film-task-group
```

before library version:

spring cloud version 2020.0.3
spring boot version 2.5.5
jdk 17

after version:
spring cloud 2020.0.4

**Comment by sobychacko** [comment]
@clay-f Could you create a small [reproducible](https://stackoverflow.com/help/minimal-reproducible-example) sample and share it with us? Thank you!

**Comment by clay-f** [comment]
[send message test](https://github.com/clay-f/spring-stream-test/tree/main)

hello, I'm have create test project, and get same issue🙂

**Comment by sobychacko** [comment]
@clay-f Thanks for the sample application. The problem is due to the following configuration:
```
producer:
            useNativeEncoding: true
```
When you set `useNativeEncoding`,  you must provide the proper Kafka serializer, in this case, the `StringSerializer`.  
The easy fix is to remove that configuration and then rely on the message conversion from Spring Cloud Stream. 

If you must use native Kafka serialization, then you need to provide the serializer explicitly (`spring.cloud.stream.kafka.binder.configuration.value.serializer`).

**Comment by SwingGuy1024** [comment]
Where (in what file) would I find the faulty configuration? It doesn't even look like a property file.
