### ISSUE TITLE
Cannot invoke "org.springframework.core.ResolvableType.getType()" because "types[0]" is null

### ISSUE THREAD

**Issue by andrashatvani** [spring-cloud/spring-cloud-stream-binder-kafka#1156]
**Describe the issue**
After upgrade of `spring-cloud-dependencies` to `3.0.4` ie. to `spring-cloud-stream-dependencies` to `3.1.4` the start of the app fails with the following failure message:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.core.ResolvableType.getType()" because "types[0]" is null
	at org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsBindableProxyFactory.<init>(KafkaStreamsBindableProxyFactory.java:83)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 92 more
```

**To Reproduce**
There's only one producer and one consumer defined with the following signatures:
```
fun projekte() = Supplier<Flux<Message<BaseEvent>>> { sink.asFlux().filter { it.payload is ProjektEvent } }
...
fun wirtschaftseinheiten() = Consumer<KStream<String, ByteArray>>
```
The failure occurs when trying to resolve `projekte`.

**Version of the framework**
`spring-cloud-dependencies` `3.0.4` / `spring-cloud-stream-dependencies` `3.1.4`

**Expected behavior**
The app starts.

**Screenshots**

**Additional context**
It works with `spring-cloud-dependencies` `3.0.3` ie. to `spring-cloud-stream-dependencies` `3.1.3` and since the app doesn't start, this is a blocker and had to downgrade.

**Comment by sobychacko** [comment]
@andrashatvani Thanks for reporting this issue.  It is now resolved through this commit. https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/bd1b49222cf9c6e463b165847571e84d77e24f7f. Backported to the 3.1.x branch as well.

**Comment by andrashatvani** [comment]
@sobychacko When is the release of this fix on the 3.1.x branch expected? And when will it be included in a 2020.0.x spring cloud release?

**Comment by sobychacko** [comment]
@andrashatvani We can do a point release of Spring Cloud Stream next week for `3.1.5`. However, the next `2020.0.5` release is only planned for later. You can manually override the binder dependencies once the release is available. Then, later on, when spring-cloud releases `2020.0.5`, you can formally get it from there. I will update you if there is any change to this release plan.

**Comment by keith-miller** [comment]
Thank you!
