### ISSUE TITLE
spring-cloud-stream-binder-kafka11 breaks deserialization of avro encoded messages with NPE

### ISSUE THREAD

**Issue by akloeber** [spring-cloud/spring-cloud-stream-binder-kafka#223]
I tried switching to the new Kafka 0.11 binder but that breaks avro deserialization:

With `spring-cloud-stream-binder-kafka11@1.3.0.RELEASE` it becomes necessary to add an explicite dependency to `spring-kafka@1.3.0.RELEASE` as version `1.1.6.RELEASE` (which is picked by Spring Cloud Stream Ditmars otherwise) causes a `java.lang.ClassNotFoundException: org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer`.

Afterwards the `ClassNotFoundException` is gone but deserialization of avro encoded messages fails with an NPE:
```
org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler@28d0315a]; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Unable to deserialize [null] using the contentType [application/vnd.someType.v1+avro] null; nested exception is java.lang.NullPointerException
  at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139)
  at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70)
  at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64)
  at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
  at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
  at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
  at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:188)
  at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$200(KafkaMessageDrivenChannelAdapter.java:63)
  at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:372)
  at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:352)
  at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:79)
  at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:73)
  at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
  at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
  at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:73)
  at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:39)
  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:875)
  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:859)
  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:810)
  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:688)
  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:576)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Unable to deserialize [null] using the contentType [application/vnd.someType.v1+avro] null; nested exception is java.lang.NullPointerException
  at org.springframework.cloud.stream.binder.MessageSerializationUtils.deserializePayload(MessageSerializationUtils.java:162)
  at org.springframework.cloud.stream.binder.MessageSerializationUtils.deserializePayload(MessageSerializationUtils.java:130)
  at org.springframework.cloud.stream.binder.MessageSerializationUtils.deserializePayload(MessageSerializationUtils.java:109)
  at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayloadIfNecessary(AbstractBinder.java:163)
  at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler.handleRequestMessage(AbstractMessageChannelBinder.java:561)
  at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
  at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
  ... 23 common frames omitted
Caused by: java.lang.NullPointerException: null
  at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
  at org.springframework.cloud.stream.binder.MessageSerializationUtils.deserializePayload(MessageSerializationUtils.java:152)
  ... 29 common frames omitted

```

When using `spring-cloud-stream-binder-kafka` with default dependencies of Spring Cloud Stream `Ditmars.RELEASE` (i.e. Kafka 0.10 client) everything works as expected.

__Environment:__

- JDK: 1.8.0_144
- Spring Boot: 1.5.7.RELEASE
- Spring Cloud Stream: Ditmars.RELEASE
- Spring Cloud Stream Binder Kafka: 1.3.0.RELEASE (artifact spring-cloud-stream-binder-kafka11)
- Spring Kafka: 1.3.0.RELEASE
- Avro: 1.8.2
- Confluent Stack (including Confluent Schema Registry): 3.3.0
- Kafka: 0.11.0.0-cp1

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>1.5.7.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-stream-dependencies</artifactId>
        <version>Ditmars.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-stream-binder-kafka11</artifactId>
        <version>1.3.0.RELEASE</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.kafka</groupId>
        <artifactId>spring-kafka</artifactId>
        <version>1.3.0.RELEASE</version>
    </dependency>
  <dependencies>
<dependencyManagement>
```

```xml
<dependencies>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream-binder-kafka11</artifactId>
  </dependency>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream-schema</artifactId>
  </dependency>
  <dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka</artifactId>
  </dependency>
  <dependency>
    <groupId>org.apache.avro</groupId>
    <artifactId>avro</artifactId>
  </dependency>
</dependencies>
```

__Config:__
```yml
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 9092
          zkNodes: zookeeper
          defaultZkPort: 2181
          configuration:
            "[client.id]": "some-service"
      bindings:
        output:
          destination: someTopic
          contentType: application/*+avro
          producer:
            useNativeEncoding: true
            partitionKeyExpression: payload.id
            partitionCount: 5
        input:
          destination: someTopic
          contentType: application/vnd.someType.v1+avro
          group: someInputGroup
          consumer:
            resetOffsets: true
            headerMode: raw
            partitioned: true
            concurrency: 3
      schemaRegistryClient:
        endpoint: http://schema-registry:8081
      schema:
        avro:
          dynamic-schema-generation-enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
```

**Comment by artembilan** [comment]
I would suggest you to use `headerMode: raw` for the producer as well:

    bindings:
        output:
          destination: someTopic
          contentType: application/*+avro
          producer:
            useNativeEncoding: true
            partitionKeyExpression: payload.id
            partitionCount: 5
            headerMode: raw // HERE

**Comment by garyrussell** [comment]
We shouldn't get to that deseriallization code when `useNativeEncoding: true` and header mode raw (which actually takes no effect since the binder now supports headers natively.

I am guessing it's because the `contentType` header is now being passed in the `ConsumerRecord` and that deserialization logic was not invoked with a `null` `contentType`.

Try setting `...kafka.bindings.output.headerPatterns=!contentType` on the producer side.

We need to make that deserialization code more robust.
