### ISSUE TITLE
Cannot run two kstream apps simultaneously with one Kafka instance

### ISSUE THREAD

**Issue by xmlking** [spring-cloud/spring-cloud-stream-binder-kafka#269]
I Cannot run two  `org.springframework.cloud:spring-cloud-stream-binder-kstream` spring-boot apps simultaneously that is configured  with single Kafka server.  

### How to reproduce:
Env:
```
kafkaVersion=0.10.1.1
springBootVersion=1.5.9.RELEASE
springCloudStreamVersion=Ditmars.RELEASE
```
example project : https://github.com/xmlking/kstream-experiments 
 `analyzer` and `product` apps cannot be started  simultaneously. I can start both of them,  one-at-a-time without error. 

### Error:

```
java.lang.IllegalArgumentException: Assigned partition products-0 for non-subscribed topic.
        at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignFromSubscribed(SubscriptionState.java:187) ~[kafka-clients-0.10.1.1.jar:na]
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:215) ~[kafka-clients-0.10.1.1.jar:na]
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:313) ~[kafka-clients-0.10.1.1.jar:na]
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:277) ~[kafka-clients-0.10.1.1.jar:na]
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:259) ~[kafka-clients-0.10.1.1.jar:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013) ~[kafka-clients-0.10.1.1.jar:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979) ~[kafka-clients-0.10.1.1.jar:na]
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:407) ~[kafka-streams-0.10.1.1.jar:na]
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:242) ~[kafka-streams-0.10.1.1.jar:na]

2017-12-25 13:43:07.275  INFO 11205 --- [ StreamThread-1] o.a.k.clients.producer.KafkaProducer     : Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
Exception in thread "StreamThread-1" java.lang.IllegalArgumentException: Assigned partition products-0 for non-subscribed topic.
        at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignFromSubscribed(SubscriptionState.java:187)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:215)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:313)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:277)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:259)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:407)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:242)

```

**Comment by olegz** [comment]
@xmlking as you can see from the stack trace this is once again not related at all to spring-cloud-stream and as @garyrussell suggested earlier when you have a question it is better to be asked on the appropriate forum such as Kafka specific Gitter and/or StackOverflow channels.

But in trying to answer your question anyway, I believe you are using the same app id.

**Comment by xmlking** [comment]
Thanks @olegz for the hint (app id)  . i am new to spring-cloud-stream.  I need to figure out how to set unique AppID. can't find any documentation on AppID.  I am using unique `spring.application.name` here https://github.com/xmlking/kstream-experiments/blob/master/product/src/main/resources/application.yml

**Comment by xmlking** [comment]
looks like we are hardcoding application.id , is there a way to overwrite StreamsConfig in my code?


```
props.put(StreamsConfig.APPLICATION_ID_CONFIG, "default");
```

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kstream/src/main/java/org/springframework/cloud/stream/binder/kstream/config/KStreamBinderSupportAutoConfiguration.java#L74

**Comment by xmlking** [comment]
@sobychacko can we keep this issue open as APPLICATION_ID_CONFIG is not exposed yet? 
which is preventing us to run more then one kstream apps on single kafka instance ?

**Comment by artembilan** [comment]
Reopen. See comment above: the ` APPLICATION_ID_CONFIG` property must be exposed.

**Comment by sobychacko** [comment]
We have a way to override this property even now using the following:
`spring.cloud.stream.kstream.binder.configuration.application.id`. Therefore, I don't think we need to do any further customizations on this from the framework.

**Comment by artembilan** [comment]
That's cool, @sobychacko !

Fully makes sense to leave it as is. And really sounds self explanatory 😄 

Now it is time to close, indeed.
