### ISSUE TITLE
ClassCastException with the latest snapshot build

### ISSUE THREAD

**Issue by tambre** [spring-cloud/spring-cloud-stream-binder-kafka#306]
Getting the following when having key as string. Was working well till last week. However, today first had to upgrade the dependency on spring-kafka to 2.1.3.BUILD-SNAPSHOT (as the empty constructor was StreamFactoryBean was not there in 2.1.2-RELEASE). Once this was resolved, started to get this error. 

tried setting:

`spring.cloud.stream.bindings.input.consumer.key.deserializer: org.apache.kafka.common.serialization.StringDeserializer`

`spring.cloud.stream.kstream.bindings.output.producer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde`

however, they were not getting set (seen in the spring-boot startup logs). 

I think this is related to changes in `KStreamListenerSetupMethodOrchestrator.java`

`Exception in thread "eventMetricRecorder-73aa1b44-a9bf-4087-9ccc-39b32f145d69-StreamThread-1" java.lang.ClassCastException: [B cannot be cast to java.lang.String
        at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:41)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:85)
        at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:85)
        at org.apache.kafka.streams.kstream.internals.KStreamPassThrough$KStreamPassThroughProcessor.process(KStreamPassThrough.java:33)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:99)
        at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:45)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:85)
        at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:85)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:216)
        at org.apache.kafka.streams.processor.internals.AssignedTasks.process(AssignedTasks.java:403)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:317)
        at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:942)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:822)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:774)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:744)
`

**Comment by tambre** [comment]
Currently to solve this, I had to change my keys to byte[] from String.

**Comment by sobychacko** [comment]
@tambre there have been some significant changes in the latest commits in the kafka binder in terms of the kafka streams support. The artifact itself is renamed, all the properties are updated. Could you checkout the latest snapshot and see if this is still a problem? We are still improving the docs, but this gives a general idea: https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.BUILD-SNAPSHOT/reference/htmlsingle/#_kafka_streams_binding_capabilities_of_spring_cloud_stream

If this still an issue, please ping here and we will take a look.

Thanks!

**Comment by sobychacko** [comment]
@tambre These two properties should work now:

`spring.cloud.stream.kafka.streams.bindings.input.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde`

`spring.cloud.stream.kafka.streams.bindings.output.producer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde`

**Comment by tambre** [comment]
@sobychacko - hi.

The new build worked. Thanks. I think we can close this issue. 
Just one thing. 

I **can't** set the following properties as "true".  Reason being: I am using Avro for serialization. If I set them then the `AvroMessageConverter` that I have defined as a bean in my Spring project - is not used. I will have to create my own deserializer (the contentType property is ignored). Not sure if I am doing something wrong. 

`spring.cloud.stream.bindings.input.consumer.useNativeDecoding: true` and
`spring.cloud.stream.bindings.output.producer.useNativeEncoding: true`

However, even without them it worked.

**Comment by sobychacko** [comment]
Hi @tambre - if you set `useNativeDecoding` or `useNativeEncoding` to true, then that means that the contentType property will be ignored and Kafka will do the de/serialization in which case you need to specify serdes. By default they are false, and the contentType property will be used for value de/serialization.

**Comment by tambre** [comment]
@sobychacko thanks for your help
