### ISSUE TITLE
Kafka Streams binder: IllegalAccessException in non-public classes with StreamListener method

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#348]
```java
org.springframework.beans.factory.BeanInitializationException: Cannot setup StreamListener for public void wc.WordsConsumer.process(org.apache.kafka.streams.kstream.KStream); nested exception is java.lang.IllegalAccessException: Class org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator can not access a member of class wc.WordsConsumer with modifiers "public"
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.orchestrateStreamListenerSetupMethod(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:195) ~[spring-cloud-stream-binder-kafka-streams-2.0.0.RC3.jar:2.0.0.RC3]
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.doPostProcess(StreamListenerAnnotationBeanPostProcessor.java:195) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.lambda$postProcessAfterInitialization$0(StreamListenerAnnotationBeanPostProcessor.java:167) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_151]
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.injectAndPostProcessDependencies(StreamListenerAnnotationBeanPostProcessor.java:285) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(StreamListenerAnnotationBeanPostProcessor.java:105) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:777) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at wc.WordCountApplication.main(WordCountApplication.java:51) [classes/:na]
Caused by: java.lang.IllegalAccessException: Class org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator can not access a member of class wc.WordsConsumer with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[na:1.8.0_151]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296) ~[na:1.8.0_151]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:491) ~[na:1.8.0_151]
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.orchestrateStreamListenerSetupMethod(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:159) ~[spring-cloud-stream-binder-kafka-streams-2.0.0.RC3.jar:2.0.0.RC3]
	... 15 common frames omitted
```

**Comment by artembilan** [comment]
You need to use `ReflectionUtils.makeAccessible(method)` before `method.invoke()`.

**Comment by garyrussell** [comment]
Huh? Why is this a bug? Where do we advertise that `@StreamListener` methods don't need to be public?

Seems bogus to me.

BTW, it would be useful when creating issues to link to the source rather than just posting a stack trace.

**Comment by sobychacko** [comment]
@garyrussell its actually not the SL method, but rather the containing class. For ex:

```java
@EnableBinding(WordCountChannels.class)
class WordsConsumer {

        @StreamListener
        public void process(@Input(WordCountChannels.WORDS_INBOUND) KStream<Object, String> words) {
```

**Comment by garyrussell** [comment]
Still bogus IMHO.

**Comment by joshlong** [comment]
Hi, please support this for consistency's sake. Here are some examples of package private components in Spring MVC, Spring Cloud Stream (+Kafka, but no Kafka Streams), and Spring Integration that all work 

```
package com.example.demo;

import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.Input;
import org.springframework.cloud.stream.annotation.Output;
import org.springframework.cloud.stream.annotation.StreamListener;
import org.springframework.context.annotation.Bean;
import org.springframework.integration.annotation.MessageEndpoint;
import org.springframework.integration.annotation.ServiceActivator;
import org.springframework.integration.dsl.channel.MessageChannels;
import org.springframework.messaging.Message;
import org.springframework.messaging.MessageChannel;
import org.springframework.messaging.SubscribableChannel;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

interface GreetingsBindings {

		String GREETINGS_OUT = "streamOut";

		String GREETINGS_IN = "streamIn";

		@Output(GREETINGS_OUT)
		MessageChannel streamOut();

		@Input(GREETINGS_IN)
		SubscribableChannel streamIn();
}

@SpringBootApplication
@EnableBinding(GreetingsBindings.class)
public class DemoApplication {

		@Bean
		MessageChannel directGreetingsOut() {
				return MessageChannels.direct().get();
		}

		private void produce(String greetings, MessageChannel channel) {
				for (int i = 0; i < 10; i++)
				   channel.send(MessageBuilder.withPayload(greetings + " #" + i).build());
		}

		@Bean
		ApplicationRunner springCloudStreamDriver(GreetingsBindings bindings) {
				return args -> {
						MessageChannel out = bindings.streamOut();
						produce("Hello Spring Cloud Stream", out);
				};
		}

		@Bean
		ApplicationRunner springIntegrationDriver() {
				return args -> {
						MessageChannel out = this.directGreetingsOut();
						produce("Hello Spring Integration", out);
				};
		}


		public static void main(String[] args) {
				SpringApplication.run(DemoApplication.class, args);
		}
}

@Component
class HiStreamListener {

		@StreamListener(GreetingsBindings.GREETINGS_IN)
		public void hi(String msg) {
				System.out.println(msg);
		}
}

@MessageEndpoint
class HiServiceActivator {

		@ServiceActivator(inputChannel = "directGreetingsOut")
		public void hi(Message<String> m) {
				System.out.println(m.getPayload());
		}
}

@RestController
class HiController {

		@GetMapping("/hi")
		String hi() {
				return "Hello";
		}
}
```

I used the following Maven build 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Finchley.M9</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-integration</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>


</project>

```

and the following `application.properties`

```
spring.cloud.stream.bindings.streamOut.destination=greetings
spring.cloud.stream.bindings.streamIn.destination=greetings
```

**Comment by olegz** [comment]
FWIW, I am with Gary on this. Just because we can doesn't mean we should.

**Comment by olegz** [comment]
Also, I've reclassified it as an 'enhancement' as there should never have been an expectation of it working.

**Comment by sobychacko** [comment]
@olegz @garyrussell but why are we requiring the top level class to be public. Shouldn't we allow the users to choose the right modifier as they see fit - be it public or package-private etc.?

**Comment by joshlong** [comment]
please do support it? It's supported everywhere in Spring. Even in Spring Framework. I can't think of a framework that doesn't support it, except Spring Data REST [*]. It's why we have `ReflectionUtils#makeAccessible()` in Spring Framework itself. All those other places support that expressly. It doesn't just accidentally work, we've gone out of our way to make it work this way. Even Spring Cloud Stream, otherwise, supports this usage. Same with Spring Integration. Please fix this, otherwise it would be confusingly inconsistent with the rest of Spring. 

1. in Spring Data REST `public` means turn an interface into a REST repo, where anything less means just leave it as a data repository. So, package private is still supported for Spring Data interfaces, just not for Spring Data REST.

**Comment by garyrussell** [comment]
I hadn't considered the case where other types are added to the same class as in [Josh's example above](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/348#issuecomment-377089968). Such types cannot be `public`.

While I prefer to declare such classes as static within the scope of the main class, I can see some cleanliness in that style so I (reluctantly) withdraw my objection.
