### ISSUE TITLE
Kafka Spring Cloud consumer issue - Cannot convert message

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#410]
_From @visioncoder on July 14, 2018 5:11_

I am using KafkaTemplate to send a message with string payload and customized header.  The message is published fine on Kafka topic. However, the Cloud Stream consumer is not able to fetch it successfully, throwing StringIndexOutOfBoundsException 

**Consumer Versions**: 
Boot: 1.5.10.RELEASE
Spring Cloud: Edgware.SR4
Cloud Stream: Elmhurst.RELEASE

**Producer Versions:** 
Boot: 1.5.10.RELEASE
Spring Cloud: Edgware.SR3
Cloud Stream: Elmhurst.RELEASE

**Producer Code and properties:** 
```
    cloud:
        stream:
            kafka:
                binder:
                    brokers: my-brokers
                    zk-nodes: my-zookeeper
                    min-partition-count: 100
                bindings:
                    my-events:
                        producer:
                            sync: true
                    my-events-dlq:
                        producer:
                            sync: true
            bindings:
                my-events:
                    destination: my-events-env
                my-events-dlq:
                    destination: my-events-DEV-dlq

         public boolean publishEvent(String event) {
        Message<String> message = MessageBuilder.withPayload(event)
                .setHeader(KafkaHeaders.MESSAGE_KEY, UUID.randomUUID().toString().getBytes())
                .build();
        boolean isSent = messageChannels.myEvents().send(message, 2000);
    
```

**Relevant Consumer Code and properties**: 
```
 bindings:
                some-events-channel:
                    destination: my-events
                    group: ${spring.application.name}-env
                    #content-type: application/json
                    #content-type: java.lang.String 
                    #content-type: text/plain

//Tried both the below options separately
    @StreamListener(EventChannel.SOME_CHANNEL)
    public void listenEvent(Message<String> message) {
              LOG.info(....);
    }


    @StreamListener(EventChannel.SOME_CHANNEL)
    public void listenEvent(ConsumerRecord<String, String> message ) {
              LOG.info(....);
    }

```

**Stack Trace:** 
```
2018-07-14 00:54:11.259 ERROR [           -L-1] o.s.c.s.b.k.KafkaMessageChannelBinder    : Could not convert message: 3C3F786D6C2076657273696F6E3D27312E302720656E636F64696E673D275554462D38273F3E3C726573656C6C65724450464F4576656E744E6F74696669636174696F6E207873693A736368656D614C6F636174696F6E3D27687474703A2F2F7777772E766572697A6F6E776972656C6573732E636F6D2F6F617320687474703A2F2F6C6F63616C686F73743A383038352F736368656D612F726573656C6C65722E7873642720786D6C6E733D27687474703A2F2F7777772E766572697A6F6E776972656C6573732E636F6D2F6F61732720786D6C6E733A7873693D27687474703A2F2F7777772E77332E6F72672F323030312F584D4C536368656D612D696E7374616E6365273E3C6D6573736167654865616465723E3C76656E646F7249643E434F4D434153543C2F76656E646F7249643E3C72657175657374547970653E4F524445523C2F72657175657374547970653E3C6F72646572547970653E4D4E544D4C4E443C2F6F72646572547970653E3C7265666572656E63654E756D6265723E313638313934323C2F7265666572656E63654E756D6265723E3C72657475726E55524C3E68747470733A2F2F31302E3235332E3138332E3234372F6D626F7765622D6D70612D70726F642E67736C62322E636F6D636173742E636F6D2F6D626F73767A77756E736F6C6963697465646E6F74696669636174696F6E2F6170692F726573706F6E73652F756E736F6C696369746564726573706F6E73653C2F72657475726E55524C3E3C2F6D6573736167654865616465723E3C4450464F4576656E744E6F74696669636174696F6E3E3C6576656E74446174653E323031382F30372F31312032333A33393A32303C2F6576656E74446174653E3C6D646E3E343034393536323138383C2F6D646E3E3C6576656E745374617475733E4F4E3C2F6576656E745374617475733E3C2F4450464F4576656E744E6F74696669636174696F6E3E3C2F726573656C6C65724450464F4576656E744E6F74696669636174696F6E3E

java.lang.StringIndexOutOfBoundsException: String index out of range: 784
	at java.lang.String.checkBounds(String.java:385) ~[na:1.8.0_131]

```

Additionally, I have also tried setting the headerMode but no help there either: 
stream.bindings.input.consumer.header-mode: raw

Can someone please advise what I may be missing, or need to do differently? 

Thanks!

_Copied from original issue: spring-cloud/spring-cloud-stream#1416_

**Comment by sabbyanandan** [comment]
_From @olegz on July 16, 2018 6:43_

Can you please post a full stack trace? What you included above is not it as it contains no information to diagnose the issue.

**Comment by visioncoder** [comment]
Hi @sabbyanandan  thank you for your response. 

Attached please find the full stack trace: 

```
2018-07-16 14:20:20.424 ERROR [           -L-1] o.s.c.s.b.k.KafkaMessageChannelBinder    : Could not convert message: 3C3F786D6C2076657273696F6E3D22312E302220656E636F64696E673D225554462D3822207374616E64616C6F6E653D22796573223F3E3C726573656C6C65724450464F4576656E744E6F74696669636174696F6E20786D6C6E733D22687474703A2F2F7777772E766572697A6F6E776972656C6573732E636F6D2F6F6173223E3C6D6573736167654865616465723E3C76656E646F7249643E56454E444F525F49443C2F76656E646F7249643E3C72657175657374547970653E5245515F545950453C2F72657175657374547970653E3C6F72646572547970653E4F524445523C2F6F72646572547970653E3C7265666572656E63654E756D6265723E30373035323335372D313030303334353336323C2F7265666572656E63654E756D6265723E3C72657475726E55524C3E52455455524E5F55524C3C2F72657475726E55524C3E3C6173796E634572726F7255524C3E6179736E633C2F6173796E634572726F7255524C3E3C2F6D6573736167654865616465723E3C4450464F4576656E744E6F74696669636174696F6E3E3C6576656E74446174653E323031382D30372D30355432333A35373A30362E3036345A3C2F6576656E74446174653E3C6D646E3E313030303334353336323C2F6D646E3E3C6576656E745374617475733E4558484155535445443C2F6576656E745374617475733E3C70726F6D6F74696F6E49443E50524F4D4F5F49443C2F70726F6D6F74696F6E49443E3C2F4450464F4576656E744E6F74696669636174696F6E3E3C2F726573656C6C65724450464F4576656E744E6F74696669636174696F6E3E

java.lang.StringIndexOutOfBoundsException: String index out of range: 667
	at java.lang.String.checkBounds(String.java:385) ~[na:1.8.0_131]
	at java.lang.String.<init>(String.java:425) ~[na:1.8.0_131]
	at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.oldExtractHeaders(EmbeddedHeaderUtils.java:154) ~[spring-cloud-stream-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.extractHeaders(EmbeddedHeaderUtils.java:115) ~[spring-cloud-stream-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.extractHeaders(EmbeddedHeaderUtils.java:107) ~[spring-cloud-stream-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler.handleRequestMessage(AbstractMessageChannelBinder.java:546) ~[spring-cloud-stream-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109) [spring-integration-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) [spring-integration-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70) [spring-integration-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64) [spring-integration-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) [spring-messaging-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) [spring-messaging-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) [spring-messaging-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:188) [spring-integration-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$200(KafkaMessageDrivenChannelAdapter.java:63) [spring-integration-kafka-2.1.2.RELEASE.jar:na]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:372) [spring-integration-kafka-2.1.2.RELEASE.jar:na]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:352) [spring-integration-kafka-2.1.2.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:79) [spring-kafka-1.1.7.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:73) [spring-kafka-1.1.7.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) [spring-retry-1.2.2.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) [spring-retry-1.2.2.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:73) [spring-kafka-1.1.7.RELEASE.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:39) [spring-kafka-1.1.7.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:792) [spring-kafka-1.1.7.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:736) [spring-kafka-1.1.7.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.access$2100(KafkaMessageListenerContainer.java:246) [spring-kafka-1.1.7.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ListenerInvoker.run(KafkaMessageListenerContainer.java:1025) [spring-kafka-1.1.7.RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

```

**Comment by visioncoder** [comment]
Hi @sabbyanandan 

Quick update: If I specify content-type as plain/text and set headerMode to raw, it works. Like so: 
```
            bindings:
                my-events-topic:
                    destination: specfiic-events-dev
                    group: ${spring.application.name}-dev
                    content-type: text/plain
                    consumer:
                        headerMode: raw
```
I should not really have to do that, correct?

**Comment by garyrussell** [comment]
Yes; you need to specify `headerMode: raw` with spring-cloud-streaam 1.3.x. It is not needed in 2.0.x.

**Comment by visioncoder** [comment]
Hi @garyrussell thank you. 

Understood the `headerMode` part. But not sure I quite get having to specify `content-type: text/plain`. It  gives the same error/stack trace when I configure it as `content-type: application/json`

**Comment by garyrussell** [comment]
That's not possible; it must be a different error; the `EmbeddedHeaderUtils` is not invoked if the `headerMode` is `raw`.

**Comment by garyrussell** [comment]
Yes; with Elmhurst, if you provide no conversion hints (`Message<?>` message) you will get a `byte[]` payload. `(Message<String> message)` or `(String message)`  will allow the framework to do the conversion.

**Comment by sobychacko** [comment]
@visioncoder Are you good with this issue? If so, can we close this?

**Comment by sabbyanandan** [comment]
Closing this due to no activity.
