### ISSUE TITLE
Fix JAAS initializer with missing properties

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#419]
Original title of the issue: Not able to bind to multiple binders for Spring-cloud-stream kafka

_From @pathiksheth14 on July 1, 2018 15:7_

I am trying to bind two kafka broker and send and consume messages from both. But while initializing only one broker gets connected, the first one. Second one always fails.

Further debugging shows that for the second broker fails in Fetcher.java:

client.poll(future, remaining); returns org.apache.kafka.common.errors.DisconnectException. 

When I run both this broker individually both works fine.

I am using 1.5.8.RELEASE of spring boot and Dalston.SR4 for spring cloud.

application.yml is attached.
[application.txt](https://github.com/spring-cloud/spring-cloud-stream/files/2152871/application.txt)

This is really important for me. Any input will be of great help.

_Copied from original issue: spring-cloud/spring-cloud-stream#1404_

**Comment by sobychacko** [comment]
_From @olegz on July 1, 2018 16:6_

Could you please attach stack trace, so we can see the actual error you're having?

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 1, 2018 16:50_

Hi Oleg,

    Thank you for quick response.

    I will be able to share logs tomorrow as I return to work.

    As per my understanding it will take more than 10 mins to throw error as wait time is around 60000 ms and there are 10 attempts and further wait while doing client.send(future, something);

    In mean time can you have a look at yml and see if something wrong there.Some configuration that is not proprely defined.

    I also want to check whether this is expected scenario and not a limitation for Dalston.SR4.

Thanks,
Pathiik

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 2, 2018 10:29_

@olegz  I tried same configuration again its been 30 mins and its still executing. It keep retrying connection check. Here is the log it keep printing after every 5 min. 

After 30 mins it returns the thread till then server remain non responding.

```
2018-07-02 15:48:05.907  INFO 14264 --- [  restartedMain] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	auto.commit.interval.ms = 100
	auto.offset.reset = earliest
	bootstrap.servers = [*****************************]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = FNV_SECURITIES
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = PLAIN
	security.protocol = SASL_PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

2018-07-02 15:48:05.909  INFO 14264 --- [  restartedMain] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	auto.commit.interval.ms = 100
	auto.offset.reset = earliest
	bootstrap.servers = [*********************]
	check.crcs = true
	client.id = consumer-7
	connections.max.idle.ms = 540000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = FNV_SECURITIES
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = PLAIN
	security.protocol = SASL_PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

2018-07-02 15:48:05.917  INFO 14264 --- [  restartedMain] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 0.10.1.1
2018-07-02 15:48:05.917  INFO 14264 --- [  restartedMain] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : f10ef2720b03b247

```

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 2, 2018 11:19_

Error after 60000 ms.
```
2018-07-02 16:32:07.467 ERROR 13196 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is org.springframework.cloud.stream.binder.BinderException: Cannot initialize binder:
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at com.bnym.fnv.QueryServiceApplication.main(QueryServiceApplication.java:30) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.8.RELEASE.jar:1.5.8.RELEASE]
Caused by: org.springframework.cloud.stream.binder.BinderException: Cannot initialize binder:
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:271) ~[spring-cloud-stream-binder-kafka-core-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:149) ~[spring-cloud-stream-binder-kafka-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:88) ~[spring-cloud-stream-binder-kafka-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:112) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:124) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:238) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	... 19 common frames omitted
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

Disconnected from the target VM, address: '127.0.0.1:61512', transport: 'socket'

Process finished with exit code 0
```

**Comment by sobychacko** [comment]
_From @olegz on July 2, 2018 15:4_

This seems to be pointing to a miss-configured Kafka producer/consumer. If you google around there are plenty of references to `org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.` You should also the kafka service logs which may contain more details.
Also, in your configuration you pointing to` kafka1` and `kafka2` binders, but configure `cnj` and `tpc`. . . . Not sure what you're trying to do there.

Please consider following [this section](https://docs.spring.io/spring-cloud-stream/docs/Ditmars.SR4/reference/htmlsingle/#multiple-binders) for multi-binder configurations

**Comment by sobychacko** [comment]
@pathiksheth14 here is a [sample application](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multibinder-samples/multibinder-two-kafka-clusters) that uses two kafka clusters and bind to both of them. You might want to compare your application with this.

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 2, 2018 15:55_

@olegz  both this binder works fine if I remove one and run other one individually. That means binders are pointing to right kafka cluster/brokers.

cnj and tpc are our internal representation. I didn't wanted to share it so renamed it to tpc and cnj.

**Comment by sobychacko** [comment]
_From @olegz on July 2, 2018 15:58_

All I am saying is that your configuration appears incorrect, so there is nothing for us to go by other then provide you with a working example (as Soby did), so please follow the example application while modifying configuration with values representing your environment and let us know

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 2, 2018 16:0_

@sobychacko I have configured my project by using exact same example.

But when I use your project and configure yaml file using our cluster and jaas configurations, it gives login error. I think springboot 2.0.0,kafka 2.0.0.Release and Finchley.Release are not reading jaas config from my yaml file. Is there any change in jaas configuration for latest versions.

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 2, 2018 16:7_

@olegz 

Thank you for quick response. Here is my config file. 
```
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      enabled: false
    stream:
      kafka:
        binder:
          jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
          configuration:
            "[security.protocol]": SASL_PLAINTEXT
            "[sasl.mechanism]": PLAIN
      bindings:
        sampleQueueA:
          destination: FNV_HOLDINGS
          binder: tpc
          group: FNV_HOLDINGS
        sampleQueueB:
          destination: FNV_SECURITIES
          binder: cnj
          group: FNV_SECURITIES
      binders:
        tpc:
         type: kafka
         defaultCandidate: false
         inheritEnvironment: false
         environment:
           spring:
             cloud:
               stream:
                kafka:
                  binder:
                    brokers: ${broker1}
                    autoCreateTopics: false
                    jaas:
                      options:
                        username: ${username1}
                        password: ${password1}
        cnj:
         type: kafka
         defaultCandidate: false
         inheritEnvironment: false

         environment:
           spring:
             cloud:
               stream:
                kafka:
                  binder:
                    brokers: ${broker2}
                    autoCreateTopics: false
                    jaas:
                      options:
                        username: ${username2}
                        password: ${password2}

```
If I use tpc binder for both topics it works fine. If use cnj binder for both topics it works fine. It give problem when I use tpc for one cnj for one.

Our topic names are same in both this binder. Can this be an issue(though from my debugging I think that should not be an issue)?

**Comment by sobychacko** [comment]
@pathiksheth14 Any chance you can create a small application in which you re-create this issue and share with us? That way, we can run it on our end and debug more effectively.

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 2, 2018 16:17_

@sobychacko , Sure I will do that asap.

Thank you

**Comment by sobychacko** [comment]
_From @olegz on July 6, 2018 13:9_

@pathiksheth14 were you able to create a sample app that reproduces the issue that we can look at? Also, have you tried a sample provided by Soby?

**Comment by sobychacko** [comment]
_From @olegz on July 11, 2018 14:0_

Closing it as stale. No response from user and no way to reproduce

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 17, 2018 14:49_

Hi @olegz/ @sobychacko ,

Sorry for the delayed response. We had deadlines and we went ahead with single broker at the moment. I was very much occupied with it and that's why could not revert back. 

I am working with this [sample application](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multibinder-samples/multibinder-two-kafka-clusters) to come up with solution for our app.

Please let me know whether I should raise another ticket or is there any other forum where I can raise it.

I have used exactly same code by providing below yml. Right now I am facing issue while connecting to kafka servers because its not reading jaas parameters. I have debugged code and came up with below yml such that in DefaultBinderFactory while calling below line

```
ConfigurableApplicationContext binderProducingContext = springApplicationBuilder.run((String[])args.toArray(new String[args.size()]));
```
it has below args
```
0 = "--spring.cloud.stream.kafka.binder.jaas.options.username=abcdxyz"
1 = "--spring.cloud.stream.kafka.binder.jaas.loginModule=org.apache.kafka.common.security.plain.PlainLoginModule"
2 = "--spring.cloud.stream.kafka.binder.jaas.options.password=abcdxyz"
3 = "--spring.cloud.stream.kafka.binder.brokers=kafkainstance1:9092"
4 = "--spring.jmx.default-domain=nullbinder.kafka1"
```

I can see same args in applicationArguments of SpringApplication.java but in AppConfigurationEntry this values are not reflecting and this is what I see:

com.sun.security.auth.module.Krb5LoginModule

Can you review this yml? I tried a lot but could not resolve this.

```
spring:
  cloud:
    stream.kafka.binder.configuration.[security.protocol]: SASL_PLAINTEXT
    stream.kafka.binder.configuration.[sasl.mechanism]: PLAIN
    stream.kafka.binder.jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
    stream:
      bindings:
        input:
          destination: F_H_LOCAL
          binder: kafka1
          group: testGroup
        output:
          destination: F_S_LOCAL
          binder: kafka2
        #Test sink binding (used for testing)
        output1:
          destination: F_H_LOCAL
          binder: kafka1
        #Test sink binding (used for testing)
        input1:
          destination: F_S_LOCAL
          binder: kafka2
      binders:
        kafka1:
         type: kafka
         environment:
           spring:
             cloud:
               stream:
                kafka:
                  binder.brokers: kafkainstance1:9092
                  binder.jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
                  binder.jaas.options.username: abcdxyz
                  binder.jaas.options.password: abcdxyz
        kafka2:
         type: kafka
         environment:
           spring:
             cloud:
               stream:
                 kafka:
                   binder:
                     brokers: kafkainstance2:9092
                     jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
                     jaas.options.username: abcdxyz
                     jaas.options.password: abcdxyz

```

**Comment by sobychacko** [comment]
_From @olegz on July 17, 2018 14:54_

@pathiksheth14 We've seen some issues recently with multi-binder support and addressed them prior to releasing 2.0.1 (service release). While @sobychacko will take a look a bit deeper, would you mind running a quick test against the 2.0.1? For details please see https://spring.io/blog/2018/07/12/spring-cloud-stream-elmhurst-sr1-released

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 18, 2018 9:10_

I tried with 2.0.1.RELEASE version for spring-cloud-stream-binder-kafka and spring-cloud-stream-binder-kafka-core and spring-cloud-stream version of Elmhurst.SR1 but faced the same issue.

**Comment by sobychacko** [comment]
_From @pathiksheth14 on July 26, 2018 16:32_

Hi @olegz / @sobychacko 
     Did you get chance to look into this?

**Comment by sobychacko** [comment]
@pathiksheth14 We will look at this issue soon and get back to you with any updates.

**Comment by sobychacko** [comment]
@pathiksheth14 I am going to close this issue and move this over to the kafka binder repository. This turned out to be a bug on the binder side. We will fix it and backport to 2.0.x.

**Comment by sobychacko** [comment]
@pathiksheth14 PR is issued for fixing the JAAS Issues: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/421
I tested the PR, using a sample here: https://github.com/schacko-samples/kafka-multibinder-jaas

**Comment by sobychacko** [comment]
@pathiksheth14 - This PR is merged on the master branch. Can you please check it out and see if it resolves your issues?

**Comment by sabbyanandan** [comment]
Addressed via https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/7007f9494a2f43e066141dda90c85cde62a83f1c.
