### ISSUE TITLE
Multibinder with Kafka Streams not work

### ISSUE THREAD

**Issue by davbur** [spring-cloud/spring-cloud-stream-binder-kafka#504]
If you try to configure multibinder with kafka streams doesn't work

```yml
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: dataIn
          binder: kafka1
          group: testGroup
        output:
          destination: dataOut
          binder: kafka1
        input2:
          destination: dataOut2
          binder: kafka2
          group: testGroup2
      binders:
        kafka1:
         type: kafka
         environment:
           spring:
             cloud:
               stream:
                kafka:
                  binder:
                    brokers: ${kafkaBroker1}
                    zkNodes: ${zk1}
        kafka2:
         type: kafka
         environment:
           spring.cloud.stream.kafka.streams.binder:
             brokers: ${kafkaBroker2}
```

Exception error:

```
org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.IllegalStateException: The binder 'kafka2' cannot bind a com.sun.proxy.$Proxy100
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.1.0.BUILD-20181030.064057-619.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.0.BUILD-20181030.064057-619.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.BUILD-20181030.064057-619.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.BUILD-20181030.064057-619.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.BUILD-20181030.064057-619.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.BUILD-20181030.064057-619.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.BUILD-20181030.064057-619.jar:2.1.0.BUILD-SNAPSHOT]
	at multibinder.MultibinderApplication.main(MultibinderApplication.java:26) [classes/:na]
Caused by: java.lang.IllegalStateException: The binder 'kafka2' cannot bind a com.sun.proxy.$Proxy100
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:171) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:120) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:313) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:94) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:234) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:54) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_121]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:33) ~[spring-cloud-stream-2.1.0.BUILD-20181121.182846-229.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	... 14 common frames omitted
```

To reproduce the error I mixed the examples:

https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multibinder-samples/multibinder-two-kafka-clusters

https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-aggregate

**Comment by davbur** [comment]
If you remove @Ignore, this test ends in ERROR

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/v2.1.0.RC2/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/bootstrap/KafkaStreamsBinderBootstrapTest.java

**Comment by lherrera** [comment]
Could you send the code resulting from mixing both examples?

**Comment by olegz** [comment]
@davbur Also, please provide version of spring-cloud-stream so we can diagnose it properly

**Comment by davbur** [comment]
> Could you send the code resulting from mixing both examples?

https://github.com/davbur/spring-cloud-stream-samples/tree/example-multibinder-kafka-streams/multibinder-samples/multibinder-kafka-streams

**Comment by davbur** [comment]
> @davbur Also, please provide version of spring-cloud-stream so we can diagnose it properly

2.1.0.RC2 and 2.1.0.BUILD-SNAPSHOT

**Comment by sobychacko** [comment]
@davbur is `2.1.0.BUILD-SNAPSHOT` for the kafka/streams binder?

**Comment by davbur** [comment]
> @davbur is `2.1.0.BUILD-SNAPSHOT` for the kafka/streams binder?

Yes, also 2.1.0.RC2

**Comment by sobychacko** [comment]
@davbur @lherrera [Here is a sample](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multibinder-samples/multibinder-kafka-streams) that works with multi binders (kafka and kafka streams).  Please take a look at the yaml configuration. Notice that the kafka streams specific [properties](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/multibinder-samples/multibinder-kafka-streams/src/main/resources/application.yml#L6) are provided outside of the `enrionment`. This is a current limitation which I am trying to fix. But regardless, this sample should get you going. I will issue a PR in the binder to unignore those tests you mentioned.
