### ISSUE TITLE
unable to set ssl.endpoint.identification.algorithm to empty

### ISSUE THREAD

**Issue by VasuBhaskar** [spring-cloud/spring-cloud-stream-binder-kafka#520]
Kafka documentation says as below(leave ssl.endpoint.identification.algorithm as empty to disable host name verification  ).

`Caused by: java.lang.IllegalArgumentException: Invalid argument syntax: --spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=
        at org.springframework.core.env.SimpleCommandLineArgsParser.parse(SimpleCommandLineArgsParser.java:75) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.core.env.SimpleCommandLinePropertySource.<init>(SimpleCommandLinePropertySource.java:90) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
`

Apparently SimpleCommandLineArgsParser does not allow empty values

`if(optionName.isEmpty() || optionValue != null && optionValue.isEmpty()) {
          throw new IllegalArgumentException("Invalid argument syntax: " + arg);
        }
`

This happens in Greenwich Release

**Comment by VasuBhaskar** [comment]
This is still an issue and i had to switch to Finchley.RELEASE to overcome this issue. Any help would be much appreciated

**Comment by sobychacko** [comment]
@VasuBhaskar Do you have more stack trace information? That code in [SimpleCommandLineArgsParser](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/env/SimpleCommandLineArgsParser.java) has not changed any time recently.

**Comment by VasuBhaskar** [comment]
This is not happening because of code changed in SimpleCommandLineArgsParser . Greenwich Release uses kafka api version 2.0.0 which defaults to https

`<properties>
		<java.version>1.8</java.version>
		<spring-kafka.version>2.2.2.RELEASE</spring-kafka.version>
		<spring-integration-kafka.version>3.1.0.RELEASE</spring-integration-kafka.version>
		<kafka.version>2.0.0</kafka.version>
		<spring-cloud-stream.version>2.1.0.BUILD-SNAPSHOT</spring-cloud-stream.version>
`
Kafka documentation says as below to avoid host check

`ssl.endpoint.identification.algorithm The endpoint identification algorithm used by clients to validate server host name. The default value is HTTPS. Clients including client connections created by the broker for inter-broker communication verify that the broker host name matches the host name in the broker’s certificate. Server host name verification may be disabled by setting ssl.endpoint.identification.algorithm to an empty string.

Type: string
Default: none
Importance: medium`

Because SimpleCommandLineArgsParser does not allow an empty value, there is no way to overcome this as of now

**Comment by sobychacko** [comment]
@VasuBhaskar I set this property through `application.yaml` and the application starts up fine. 
For example this is from my yaml file, 
`spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm:`
which sets it to empty. 

From console output. 
```
ssl.cipher.suites = null
ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
ssl.endpoint.identification.algorithm =
```
You can also use it as CLI property. For example,
`java -jar application.jar -Dspring.cloud.stream.kafka.streams.binder.configuration.ssl.endpoint.identification.algorithm=`
This also works.

**Comment by sabbyanandan** [comment]
Closing this due to no activity.

**Comment by testslers** [comment]
The setting should be 
spring.cloud.stream.kafka.streams.binder.configuration.ssl.endpoint.identification.algorithm=
and not
spring.cloud.stream.kafka.binder.configuration.ssl.endpoint.identification.algorithm=
