### ISSUE TITLE
add support for zstd compression

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-stream-binder-kafka#529]
https://cwiki.apache.org/confluence/display/KAFKA/KIP-110%3A+Add+Codec+for+ZStandard+Compression
Currently not supported in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaProducerProperties.java

**Comment by olegz** [comment]
Not sure but perhaps it is more relevant to spring-kafka? @garyrussell ?

**Comment by garyrussell** [comment]
Also, this logic in the provisioner needs to be improved...

```java
try {
	//This call may return null or throw an exception.
	partitions = callable.call();
}
catch (Exception ex) {
	//The above call can potentially throw exceptions such as timeout. If we can determine
	//that the exception was due to an unknown topic on the broker, just simply rethrow that.
	if (ex instanceof UnknownTopicOrPartitionException) {
		throw ex;
	}
}
```

The actual exception is eaten; it should be at least logged.

In this case, the actual `KafkaException` has a cause:

    java.lang.IllegalArgumentException: Unknown compression name: zstd

But at runtime, all we see is...

```
org.springframework.cloud.stream.binder.BinderException: Cannot initialize binder:
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:451) ~[spring-cloud-stream-binder-kafka-core-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:284) ~[spring-cloud-stream-binder-kafka-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:132) ~[spring-cloud-stream-binder-kafka-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:178) ~[spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:93) ~[spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:139) ~[spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binding.BindingService.doBindProducer(BindingService.java:249) [spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:228) [spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindOutputs(BindableProxyFactory.java:262) [spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:55) [spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_191]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47) ~[spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34) [spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.example.demo.Kbgh529Application.main(Kbgh529Application.java:13) ~[classes/:na]
Caused by: java.lang.IllegalStateException: The number of expected partitions was: 1, but 0 has been found instead
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.lambda$getPartitionsForTopic$2(KafkaTopicProvisioner.java:441) ~[spring-cloud-stream-binder-kafka-core-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164) ~[spring-retry-1.2.3.RELEASE.jar:na]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:404) ~[spring-cloud-stream-binder-kafka-core-2.1.0.RC4.jar:2.1.0.RC4]
	... 25 common frames omitted
```

**Comment by cforce** [comment]
@garyrussell  Thanks a lot for that helpful hints. Do you know if the property/and overriding kafka client, also works for Chelsey?

**Comment by olegz** [comment]
Chelsey is pretty old, soon to be EOL. Any reason why you can't upgrade?

**Comment by sabbyanandan** [comment]
Based on the discussion, we will be adding the missing ENUMs to `KafkaProducerProperties` inner-class.

**Comment by garyrussell** [comment]
> Do you know if the property/and overriding kafka client, also works for Chelsey?

I very much doubt the old Chelsea apps are compatible with the 2.1.0 kafka-clients; but YMMV.
