### ISSUE TITLE
Support Tombstones on input and output

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-kafka#531]
Reference: https://stackoverflow.com/questions/54257687/unable-to-send-message-with-kafkanull-as-value/54259169#54259169

The outbound message converters should pass `KafkaNull` unchanged.

```java
@SpringBootApplication
@EnableBinding(Source.class)
public class So54257687Application {

	public static void main(String[] args) {
		SpringApplication.run(So54257687Application.class, args);
	}

	@Bean
	public ApplicationRunner runner(MessageChannel output) {
		return args -> output.send(new GenericMessage<>(KafkaNull.INSTANCE));
	}

	@KafkaListener(id = "foo", topics = "output")
	public void listen(@Payload(required = false) byte[] in) {
		System.out.println(in);
	}

}
```
```

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.example.So54257687Application.main(So54257687Application.java:20) [classes/:na]
Caused by: org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'output'; nested exception is java.lang.IllegalStateException: Failed to convert message: 'GenericMessage [payload=org.springframework.kafka.support.KafkaNull@1dcca8d3, headers={id=dfe37902-b761-31ad-c840-93b32fda89c8, contentType=application/json, timestamp=1547833737274}]' to outbound message.
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInDeliveryExceptionIfNecessary(IntegrationUtils.java:166) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:483) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.example.So54257687Application.lambda$0(So54257687Application.java:25) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	... 5 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to convert message: 'GenericMessage [payload=org.springframework.kafka.support.KafkaNull@1dcca8d3, headers={id=dfe37902-b761-31ad-c840-93b32fda89c8, contentType=application/json, timestamp=1547833737274}]' to outbound message.
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$OutboundContentTypeConvertingInterceptor.doPreSend(MessageConverterConfigurer.java:325) ~[spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$AbstractContentTypeInterceptor.preSend(MessageConverterConfigurer.java:353) ~[spring-cloud-stream-2.1.0.RC4.jar:2.1.0.RC4]
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:607) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:443) ~[spring-integration-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
```

**Comment by garyrussell** [comment]
This works...

```java
@SpringBootApplication
@EnableBinding(Source.class)
public class So54257687Application {

	public static void main(String[] args) {
		SpringApplication.run(So54257687Application.class, args);
	}

	@Bean
	public ApplicationRunner runner(MessageChannel output) {
		return args -> output.send(new GenericMessage<>(KafkaNull.INSTANCE));
	}

	@KafkaListener(id = "foo", topics = "output")
	public void listen(@Payload(required = false) byte[] in) {
		System.out.println(in);
	}

	@Bean
	@StreamMessageConverter
	public MessageConverter kafkaNullConverter() {
		class KafkaNullConverter extends AbstractMessageConverter {

			KafkaNullConverter() {
				super(Collections.emptyList());
			}

			@Override
			protected boolean supports(Class<?> clazz) {
				return KafkaNull.class.equals(clazz);
			}

			@Override
			protected Object convertFromInternal(Message<?> message, Class<?> targetClass, Object conversionHint) {
				return message.getPayload();
			}

			@Override
			protected Object convertToInternal(Object payload, MessageHeaders headers, Object conversionHint) {
				return payload;
			}

		}
		return new KafkaNullConverter();
	}

}
```

**Comment by aldex32** [comment]
Hi @garyrussell ,
what is needed to be done for this issue? Is adding the message converter enough? If yes, in which project should this converter be added?

**Comment by garyrussell** [comment]
@aldex32 I think the `KafkaNullConverter` just needs to be added as a `@Bean` to the `KafkaBinderConfiguration` `@Configuration` class in the kafka binder project.
