### ISSUE TITLE
Exception when using kafka and kafka-stream binders in the same app

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#588]
This looks like a benign exception but is annoying when running tests. Noticed when both `spring-cloud-stream-binder-kafka` and `spring-cloud-stream-binder-kafka-stream` are in the classpath. Here is the stack trace.

```
java.lang.ClassCastException: com.sun.proxy.$Proxy90 cannot be cast to org.springframework.messaging.MessageChannel
	at org.springframework.cloud.stream.test.binder.TestSupportBinder.bindConsumer(TestSupportBinder.java:67) ~[spring-cloud-stream-test-support-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:144) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:112) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:254) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_161]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:48) ~[spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) [spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
```

**Comment by boonware** [comment]
@sobychacko Any update on this? I am seeing the same error but unsure if it's the root cause why my Kafka Streams tests are failing with the Test Support Binder.

**Comment by NandAtTSB** [comment]
I am getting the same exception while using them together. I am using functional style approach with KStreams without having the Processor. Any updates on this?

**Comment by sobychacko** [comment]
@boonware @NandAtTSB Sorry for the delay in responding to this issue. Here are some details.
The usage of `spring-cloud-stream-test-support` is discouraged in the 3.0.x versions of Spring Cloud Stream. The recommended artifact for testing message channel based binders is the [new Spring Integration based test binder](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.3.RELEASE/reference/html/spring-cloud-stream.html#_testing). With this new test binder, you no longer need the legacy `spring-cloud-stream-test-support` binder. Here is a [sample](https://github.com/schacko-samples/gh-588), where I have both Kafka and Kafka Streams binders in the classpath that also includes this new test binder dependency. The provided test passes without throwing any exceptions in the log. Please note that in the sample, I don't make use of the regular Kafka binder or the test binder. I just provided them to show how they can all co-exist in the same app without causing any issues. 

If you must use the old test binder (`spring-cloud-stream-test-binder`), then you have to isolate the Kafka Streams specific tests to a test class and then exclude the `TestSupportBinderAutoConfiguration`. See [these comments](https://github.com/schacko-samples/gh-588/blob/master/src/test/java/com/example/gh588/Gh588ApplicationTests.java#L26) for more details.

Hope this helps. I am closing this issue. If you are still facing issues with this, please feel free to re-open this and add more details.

**Comment by NandAtTSB** [comment]
No worries.  I figured out too by myself but thanks @sobychacko  for confirming that.

**Comment by terryf82** [comment]
@sobychacko is there any chance this could still be affecting 3.0.8? We have a SpringBootApplication that only makes use of the kafka-streams-binder:

```
...
implementation 'org.springframework.cloud:spring-cloud-stream:3.0.8.RELEASE'
implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams:3.0.8.RELEASE'
...
```

Yet our tests are still throwing a ClassCastException similar to the one discussed:
```
java.lang.ClassCastException: com.sun.proxy.$Proxy79 cannot be cast to org.springframework.messaging.MessageChannel
```

**Comment by venkatesh010** [comment]
@sobychacko I tried this to run my spring cloud contract tests which requires spring cloud stream on classpath and normal message collector tests together

On basetest I have put

@ImportAutoConfiguration(TestChannelBinderConfiguration.class)
@EnableAutoConfiguration(exclude = TestSupportBinderAutoConfiguration.class)

And Im getting exceptions, w.r.t 
Error creating bean messageCollector
