### ISSUE TITLE
java.io.IOException: Packet len352518912 is out of range!

### ISSUE THREAD

**Issue by altfatterz** [spring-cloud/spring-cloud-stream-binder-kafka#66]
Created a Kafka cluster on `https://aiven.io/kafka`

My configuration is:

```
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: test
      kafka:
        binder:
          zk-nodes: <kafka-service>.<project>.aivencloud.com:20786
```

With a demo app:

```
@SpringBootApplication
public class SinkApplication {
    public static void main(String[] args) {
        SpringApplication.run(SinkApplication.class, args);
    }
}

@EnableBinding(Sink.class)
class LogSink {
    private static Logger logger = LoggerFactory.getLogger(LogSink.class);

    @ServiceActivator(inputChannel= Sink.INPUT)
    public void loggerSink(Object payload) {
        logger.info("Received: " + payload);
    }
}

```
using Spring Boot 1.4.1.RELEASE with Spring Cloud Camden.SR1

fails with:

```
2016-10-31 18:30:12.179  INFO 72534 --- [           main] org.I0Itec.zkclient.ZkClient             : Waiting for keeper state SyncConnected
2016-10-31 18:30:12.183  INFO 72534 --- [6.32.115:20786)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 188.166.32.115/188.166.32.115:20786. Will not attempt to authenticate using SASL (unknown error)
2016-10-31 18:30:12.214  INFO 72534 --- [6.32.115:20786)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 188.166.32.115/188.166.32.115:20786, initiating session
2016-10-31 18:30:12.283  WARN 72534 --- [6.32.115:20786)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 188.166.32.115/188.166.32.115:20786, unexpected error, closing socket connection and attempting reconnect

java.io.IOException: Packet len352518912 is out of range!
	at org.apache.zookeeper.ClientCnxnSocket.readLength(ClientCnxnSocket.java:112) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:79) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]

```

Do you know what could be the reason?

**Comment by mbogoevici** [comment]
Hi @altfatterz,

Thanks for trying out Spring Cloud Stream. 

Looks like you're pointing the Zookeeper client of the binder to your Kafka instance via the `zk-nodes` property. You should use `brokers` instead. Since you don't get access to a Zookeeper instance you may want to skip configuration and disable topic creation (and therefore the use of ZK) from within the binder - see https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/37 for a longer discussion.

**Comment by altfatterz** [comment]
Thanks Marius.

```
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: test
      kafka:
        binder:
          brokers: spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786
          auto-create-topics: false
```

I am using the above configuration, and with 1.1.1 apache-kafka version

```
        <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
			<version>1.1.1.RELEASE</version>
		</dependency>
```

I get the following:

```
2016-10-31 22:05:52.535  INFO 84673 --- [           main] o.s.i.codec.kryo.CompositeKryoRegistrar  : configured Kryo registration [40, java.io.File] with serializer org.springframework.integration.codec.kryo.FileSerializer
2016-10-31 22:05:52.849  INFO 84673 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-10-31 22:05:52.858  INFO 84673 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'integrationMbeanExporter' has been autodetected for JMX exposure
2016-10-31 22:05:52.860  INFO 84673 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'integrationMbeanExporter': registering with JMX server as MBean [org.springframework.integration.monitor:name=integrationMbeanExporter,type=IntegrationMBeanExporter]
2016-10-31 22:05:52.903  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering beans for JMX exposure on startup
2016-10-31 22:05:52.904  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel input
2016-10-31 22:05:52.906  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageChannel,name=input': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=input]
2016-10-31 22:05:52.948  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel nullChannel
2016-10-31 22:05:52.949  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageChannel,name=nullChannel': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=nullChannel]
2016-10-31 22:05:52.958  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel errorChannel
2016-10-31 22:05:52.960  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageChannel,name=errorChannel': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=errorChannel]
2016-10-31 22:05:52.989  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageHandler,name=logSink.loggerSink.serviceActivator,bean=endpoint': registering with JMX server as MBean [org.springframework.integration:type=MessageHandler,name=logSink.loggerSink.serviceActivator,bean=endpoint]
2016-10-31 22:05:53.007  INFO 84673 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageHandler,name=errorLogger,bean=internal': registering with JMX server as MBean [org.springframework.integration:type=MessageHandler,name=errorLogger,bean=internal]
2016-10-31 22:05:53.021  INFO 84673 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147483648
2016-10-31 22:05:53.021  INFO 84673 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {service-activator:logSink.loggerSink.serviceActivator} as a subscriber to the 'input' channel
2016-10-31 22:05:53.021  INFO 84673 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'application:8081.input' has 1 subscriber(s).
2016-10-31 22:05:53.022  INFO 84673 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started logSink.loggerSink.serviceActivator
2016-10-31 22:05:53.022  INFO 84673 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147482648
2016-10-31 22:05:53.022  INFO 84673 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2016-10-31 22:05:53.048  INFO 84673 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2016-10-31 22:05:53.049  INFO 84673 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application:8081.errorChannel' has 1 subscriber(s).
2016-10-31 22:05:53.049  INFO 84673 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2016-10-31 22:05:53.049  INFO 84673 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482647
2016-10-31 22:05:53.112  INFO 84673 --- [           main] com.example.SinkApplication              : No active profile set, falling back to default profiles: default
2016-10-31 22:05:53.119  INFO 84673 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6c742b84: startup date [Mon Oct 31 22:05:53 CET 2016]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@768fc0f2
2016-10-31 22:05:53.211  INFO 84673 --- [           main] o.s.c.s.b.k.c.KafkaBinderConfiguration   : AdminUtils selected: Kafka 0.10 AdminUtils
2016-10-31 22:05:53.324  INFO 84673 --- [           main] com.example.SinkApplication              : Started SinkApplication in 0.266 seconds (JVM running for 6.609)
2016-10-31 22:05:53.352  INFO 84673 --- [           main] o.s.c.s.b.k.KafkaMessageChannelBinder    : Auto creation of topics is disabled.
2016-10-31 22:05:53.520  INFO 84673 --- [           main] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786]
	ssl.keystore.type = JKS
	sasl.mechanism = GSSAPI
	max.block.ms = 60000
	interceptor.classes = null
	ssl.truststore.password = null
	client.id = 
	ssl.endpoint.identification.algorithm = null
	request.timeout.ms = 30000
	acks = 1
	receive.buffer.bytes = 32768
	ssl.truststore.type = JKS
	retries = 0
	ssl.truststore.location = null
	ssl.keystore.password = null
	send.buffer.bytes = 131072
	compression.type = none
	metadata.fetch.timeout.ms = 60000
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	batch.size = 16384
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	linger.ms = 0
2016-10-31 22:05:53.590  INFO 84673 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 0.10.0.1
2016-10-31 22:05:53.590  INFO 84673 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : a7a17cdec9eaa6c5
2016-10-31 22:05:54.236  WARN 84673 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Bootstrap broker spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786 disconnected
2016-10-31 22:05:54.633  WARN 84673 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Bootstrap broker spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786 disconnected
2016-10-31 22:05:55.027  WARN 84673 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Bootstrap broker spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786 disconnected
2016-10-31 22:05:55.417  WARN 84673 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Bootstrap broker spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786 disconnected
2016-10-31 22:05:55.854  WARN 84673 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Bootstrap broker spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786 disconnected
2016-10-31 22:05:56.292  WARN 84673 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Bootstrap broker spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786 disconnected
2016-10-31 22:05:56.711  WARN 84673 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Bootstrap broker spring-cloud-kafka.altfatterz-92bf.aivencloud.com:20786 disconnected
```

I need to provide somehow the ssl settings (ca.crt, client.crt, client.key) to the consumer. How can I do that easily?

**Comment by mbogoevici** [comment]
You're welcome!

Any properties in http://kafka.apache.org/090/documentation.html#newconsumerconfigs (and other versions of the client) can be set on the `configuration` property of a consumer binding - see http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/htmlsingle/#_kafka_consumer_properties for details.

**Comment by mbogoevici** [comment]
@altfatterz Is there something we can do to add to the answer, or can we close this?

**Comment by altfatterz** [comment]
I still have difficulties how to configure the ssl properties from the `ca.crt`, `client.crt` and `client.key` which I receive from aiven

**Comment by mbogoevici** [comment]
Ok, thanks for the update - I'll try provide an example on how to do that.

On Fri, Nov 18, 2016 at 12:06 PM, Zoltan Altfatter <notifications@github.com

**Comment by mbogoevici** [comment]
@altfatterz I took a quick look at what Aiven provides for its consumers, and the main source of confusion lies into the differences between the Kafka Python clients and the Java ones - in Python those files can be  be provided directly via properties, whereas I believe that in Java (in general, not only for Spring Cloud Stream) they must be wrapped into a truststore/keystore by the user.

**Comment by altfatterz** [comment]
Thanks Marius. Yes, not Spring Cloud Stream issue can be closed. Would be cool to create an example in the https://github.com/spring-cloud/spring-cloud-stream-samples to showcase how to connect to a Kafka cluster with client certificates.

Aiven has Java example which works:
https://support.aiven.io/hc/en-us/articles/213574085-Getting-started-with-Aiven-Kafka

Tried to use it with leverage Spring Cloud Stream as:

```
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: test
      kafka:
        binder:
          brokers: kafka-demo.altfatterz-92bf.aivencloud.com:22972
        bindings:
          security.protocol: SSL
          ssl.truststore.location: classpath:client.truststore.jks
          ssl.truststore.password: password
          ssl.keystore.type: PKCS12
          ssl.keystore.location: classpath:client.keystore.p12
          ssl.keystore.password: password
          ssl.key.password: password
          key.serializer: org.apache.kafka.common.serialization.StringSerializer
          value.serializer: org.apache.kafka.common.serialization.StringSerializer
```

but still fails with:

```
2016-11-19 14:26:05.024  INFO 18810 --- [localhost:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2016-11-19 14:26:05.055  WARN 18810 --- [localhost:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_111]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_111]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]

```

**Comment by mbogoevici** [comment]
Right - see the comment at https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/66#issuecomment-257384540 . Because they don't provide access to the zookeeper instance and require the topics to be created by the user (or using their RESTful API which we don't support ATM) you can disable topic auto-creation via: `spring.cloud.stream.kafka.binder.autoCreateTopics=false` which would get you rid of the ZK issue.

**Comment by mbogoevici** [comment]
Closing this as it is not caused a Spring Cloud Stream issue.

**Comment by kkattakindi** [comment]
@altfatterz - is the client credentials setup working for you? I am trying to do the same using spring cloud started stream kafka and the configuration is not working for me. Appreciate any input that you can provide. Thanks

I tried setting the configuration as per the documentation at http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/htmlsingle/#_kafka_consumer_properties
