### ISSUE TITLE
Too many open files using spring cloud stream 2.1 + Kafka

### ISSUE THREAD

**Issue by iguissouma** [spring-cloud/spring-cloud-stream-binder-kafka#660]
After upgrading to spring cloud stream 2.1 on a project using multi binder kafka(2 brokers) and rabbit(1 broker) we are facing too many open files problem.

The number of files opened keeps growing evry second until reaching the limit defined by the os(redhat 7.3).

I use the actuator endpoint to monitor: /actuator/metrics/process.files.open

```
{
"name": "process.files.open",
"description": "The open file descriptor count",
"baseUnit": "files",
"measurements": [
{
"statistic": "VALUE",
"value": 1686
}

]
}
```

using cmd> lsof -p pidOfProcessJavaApplication
I see a lot of TCP connection established related to brokers kafka

Using the version 2.0 of spring cloud stream the problem is not observed, the number of open files is stable around 80 files. 
There's no problem using the exact following versions:

```
 +- org.springframework.cloud:spring-cloud-stream-binder-kafka-core:jar:2.0.0.RELEASE:compile
[INFO] |  |  \- org.springframework.integration:spring-integration-kafka:jar:3.0.3.RELEASE:compile
[INFO] |  +- org.apache.kafka:kafka-clients:jar:1.0.2:compile
[INFO] |  |  +- org.lz4:lz4-java:jar:1.4:compile
[INFO] |  |  \- org.xerial.snappy:snappy-java:jar:1.1.4:compile
[INFO] |  \- org.springframework.kafka:spring-kafka:jar:2.1.10.RELEASE:compile
I'm suspecting that the upgrade to kafka-client 2.0.0 is the potential issue.
```

In a first attempt I wanted to try the spring cloud stream 2.1 with kafka-clients 1.0.2, according to docs it's possible but I'm facing an issue. Here's my maven configuration with exclusion:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream-binder-kafka</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-kafka</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka-clients</artifactId>
    <version>1.0.2</version>
</dependency>
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-kafka</artifactId>
    <version>3.1.0.RELEASE</version>
</dependency>
```
I'm having the following error:

```
java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.Consumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:741)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:698)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

It seems that the problem is not related to spring-kafka because using @kafkalistener with same servers and number of topics the number of opened files does not increase(approximately same using spring cloud stream 2.0)

Any idea about too many open files and how to diagnose? 

Thanks for you help.

**Comment by iguissouma** [comment]
I see adminclient threads keeping created.

![2019-05-27_19h05_25](https://user-images.githubusercontent.com/9085108/58432388-6f383780-80b2-11e9-9d9b-2031591d66e4.png)

I think this happens because one or more topic does not exist and I don't have permission to create it.
