### ISSUE TITLE
I get error info ：java.lang.IllegalArgumentException: Magic v1 does not support record headers

### ISSUE THREAD

**Issue by xiejiashuai** [spring-cloud/spring-cloud-stream-binder-kafka#666]
My kafka broker version is `0.10.2.1`
My spring cloud GAV is `org.springframework.cloud:spring-cloud-alibaba-dependencies:Greenwich.SR1`
My spring boot GAV is `org.springframework.boot:spring-boot-starter-parent:2.1.4.RELEASE`
Then, My kafka clients version is `2.0.1`
My spring cloud stream kafka configuration is following 
```yml
spring.cloud.stream:
      bindings:
        output:
          destination: apim-log
          content-type: application/json
          producer:
            sync: true
        input:
          destination: apim-log
          group: cid_input
          consumer:
            autoCommitOffset: false
            resetOffsets: false
            startOffset: earliest
      kafka:
        binder:
          brokers: 10.27.21.239:9092
          required-acks: 1
```

My code is following
```java
@EnableBinding({Source.class, Sink.class})
@SpringBootApplication
@EnableScheduling
@EnableFeignClients(basePackages = "com.envision.apim.rpc.feign")
public class ApimLogApplication {

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(ApimLogApplication.class, args);
        Source source = context.getBean(Source.class);
        HttpLog httpLog = new HttpLog();
        httpLog.setApiId(1L);
        httpLog.setOrgId("test");
        source.output().send(MessageBuilder.withPayload(httpLog).build());
    }

    @StreamListener(Sink.INPUT)
    public void onMessage(HttpLog httpLog, @Header(KafkaHeaders.ACKNOWLEDGMENT) Acknowledgment acknowledgment){

        System.out.println("receive message:" + httpLog.toString());
        acknowledgment.acknowledge();
    }



}

```

When i start up the application , invoke `source.output().send(MessageBuilder.withPayload(httpLog).build());`

the error is following:
```
Exception in thread "main" org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$ProducerConfigurationMessageHandler@3e216fc9]; nested exception is java.lang.IllegalArgumentException: Magic v1 does not support record headers, failedMessage=GenericMessage [payload=byte[59], headers={spanTraceId=c9a1985ead80cb56, spanId=c9a1985ead80cb56, nativeHeaders={X-B3-TraceId=[c9a1985ead80cb56], spanTraceId=[c9a1985ead80cb56], X-B3-SpanId=[c9a1985ead80cb56], spanId=[c9a1985ead80cb56], X-B3-Sampled=[0], spanSampled=[0]}, X-B3-SpanId=c9a1985ead80cb56, X-B3-Sampled=0, X-B3-TraceId=c9a1985ead80cb56, id=cee73cf1-e26a-f085-f9f9-33fae999442e, spanSampled=0, contentType=application/json, timestamp=1559786820130}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:189)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:179)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1095)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:169)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
	at com.envision.apim.ApimLogApplication.main(ApimLogApplication.java:36)
Caused by: java.lang.IllegalArgumentException: Magic v1 does not support record headers
	at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:410)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:449)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:506)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:529)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.tryAppend(ProducerBatch.java:107)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:223)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:864)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:803)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.send(DefaultKafkaProducerFactory.java:444)
	at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:381)
	at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:218)
	at org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.handleRequestMessage(KafkaProducerMessageHandler.java:382)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:169)
	... 9 more
```

How can i resolve the problem?

Can help me ?

**Comment by garyrussell** [comment]
0.10.2.1 is very old.

Upgrade to at least 0.11.0.0, which was the first to support headers (current is 2.2.0).

Or you can set the producer/consumer `headerMode` to `embeddedHeaders` and the headers will be added to the payload.

You must also specify which headers you want to transport in `spring.cloud.stream.kafka.binder.headers`.

**Comment by sabbyanandan** [comment]
Closing this dut to no activity.
