### ISSUE TITLE
Excessive logging with SASL and Kerberos

### ISSUE THREAD

**Issue by InternDan** [spring-cloud/spring-cloud-stream-binder-kafka#671]
Good morning!

I'm using this Kafka binder (2.1.0.M3) in an environment with authentication, and if the authentication side goes down/can't be communicated with, it turns out we get millions of logs a minute generated until it can reconnect. Usually this just happens for a few seconds if it does, but it causes problems for the infrastructure I'm working with. What's the best way to deal with this?

I'm currently working on getting a copy of a part of the logs so I can post them if needed.

**Comment by garyrussell** [comment]
Increase the `reconnect.backoff.ms` from its default (50ms).

https://kafka.apache.org/documentation/

BTW, the current 2.1.x version is 2.1.3.RELEASE.

Why are you still using a pre-release milestone?

**Comment by InternDan** [comment]
Hi Gary,

Thanks for the reply - I had done that in my most recent release, but it turns out that the cloud team here may have failed to turn off an old version that didn't have that setting configured that caused the logs. I'll get details from them and make sure we're talking about the right thing.

Appreciate it!

**Comment by InternDan** [comment]
Hi Gary,

To answer your version question, I'm working in a bit of a strange walled garden environment. For whatever reason that's the version that got approved, so for those reasons that's where I am. 

I've been able to check in with our site's Kafka team, and it looks like the excessive logging wasn't being caused by authenticating directly (though the backoff time change did help a little of course), but instead by network hiccups that generate a lot of logs through the Kafka client's NetworkClient class. Log is at the bottom; is there a way to disable that in the application.properties file for the program? I'm having trouble finding something directly related.

Appreciate any insight!

2019-06-25 16:05:00.780  WARN 18888 --- [container-0-C-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-3, groupId=cgsdev] Error connecting to node ch3dr030111.express-scripts.com:9092 (id: 3 rack: null)

java.io.IOException: Can't resolve address: ch3dr030111.express-scripts.com:9092
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:235) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.connect(Selector.java:214) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:864) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.access$700(NetworkClient.java:64) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1035) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:920) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:508) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:243) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:314) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) [kafka-clients-2.0.0.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:728) [spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.nio.channels.UnresolvedAddressException: null
	at sun.nio.ch.Net.checkAddress(Net.java:101) ~[na:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_121]
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:233) ~[kafka-clients-2.0.0.jar:na]
	... 19 common frames omitted

**Comment by InternDan** [comment]
Hi Gary,

To answer your version question, I'm working in a bit of a strange walled garden environment. For whatever reason that's the version that got approved, so for those reasons that's where I am.

I've been able to check in with our site's Kafka team, and it looks like the excessive logging wasn't being caused by authenticating directly (though the backoff time change did help a little of course), but instead by network hiccups that generate a lot of logs through the Kafka client's NetworkClient class. Log is at the bottom; is there a way to disable that in the application.properties file for the program? I'm having trouble finding something directly related.

Appreciate any insight!

2019-06-25 16:05:00.780 WARN 18888 --- [container-0-C-1] org.apache.kafka.clients.NetworkClient : [Consumer clientId=consumer-3, groupId=cgsdev] Error connecting to node xxxxx (id: 3 rack: null)

java.io.IOException: Can't resolve address: xxxxx
at org.apache.kafka.common.network.Selector.doConnect(Selector.java:235) ~[kafka-clients-2.0.0.jar:na]
at org.apache.kafka.common.network.Selector.connect(Selector.java:214) ~[kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:864) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.NetworkClient.access$700(NetworkClient.java:64) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1035) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:920) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:508) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:243) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:314) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175) [kafka-clients-2.0.0.jar:na]
at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) [kafka-clients-2.0.0.jar:na]
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:728) [spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.nio.channels.UnresolvedAddressException: null
at sun.nio.ch.Net.checkAddress(Net.java:101) ~[na:1.8.0_121]
at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_121]
at org.apache.kafka.common.network.Selector.doConnect(Selector.java:233) ~[kafka-clients-2.0.0.jar:na]
... 19 common frames omitted

**Comment by garyrussell** [comment]
It seems odd that anyone would approve a "pre-release" for production use.

> 2019-06-25 16:05:00.780 WARN 18888 --- [container-0-C-1] org.apache.kafka.clients.NetworkClient : [Consumer clientId=consumer-3, groupId=cgsdev] Error connecting to node xxxxx (id: 3 rack: null)

The only suggestion I have is to change the log level for `org.apache.kafka.clients.NetworkClient` to ERROR.

**Comment by InternDan** [comment]
I certainly don't disagree on the pre-release issue, but for what it's worth it seems to run well. 

Thanks for the advice on the Network Client class as well - we'd started down that road but were wondering if there was a "Spring Boot" way as well.

**Comment by garyrussell** [comment]
@InternDan You set logging levels in application.properties (or yml).

`logging.level.org.apache.kafka.clients.NetworkClient=error`

**Comment by sabbyanandan** [comment]
A solution has been provided - closing it.
