### ISSUE TITLE
Joining 2 input KStreams

### ISSUE THREAD

**Issue by mateuszjadczykDna** [spring-cloud/spring-cloud-stream-binder-kafka#701]
Has anyone encountered problems when trying to make a simple join on 2 input KStreams when using native custom SerDes(`spring.cloud.stream.default.consumer.use-native-decoding=true`)? Inputs are binded to 2 different topics.
```
public void testProcessor(
      @Input(INPUT_1) KStream<String, TestEvent> input1Stream,
      @Input(INPUT_2) KStream<String, TestEvent > input2Stream
  )  
{
    input1Stream
        .join(input2Stream,
            (event1, event2) -> { return null;},
            JoinWindows.of(TimeUnit.MINUTES.toMillis(5)),
            Joined.with(
                Serdes.String(),
                new TestEventSerde(),
                new TestEventSerde()
            )
        );
```

I get the following error:
```Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.cloud.stream.binder.kafka.streams.KStreamBoundElementFactory$KStreamWrapperHandler.invoke(KStreamBoundElementFactory.java:103) ~[spring-cloud-stream-binder-kafka-streams-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 27 common frames omitted
Caused by: java.lang.ClassCastException: class com.sun.proxy.$Proxy107 cannot be cast to class org.apache.kafka.streams.kstream.internals.KStreamImpl (com.sun.proxy.$Proxy107 is in unnamed module of loader org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader @424651d3; org.apache.kafka.streams.kstream.internals.KStreamImpl is in unnamed module of loader 'app')
	at org.apache.kafka.streams.kstream.internals.KStreamImpl.doJoin(KStreamImpl.java:437) ~[kafka-streams-2.0.1.jar:na]
	at org.apache.kafka.streams.kstream.internals.KStreamImpl.join(KStreamImpl.java:407) ~[kafka-streams-2.0.1.jar:na]
	... 34 common frames omitted
```

The failing line(KStreamImpl.java:437):
```
KStreamImpl<K, V1> joinOther = (KStreamImpl<K, V1>) other;
```

After some digging it seems that input2Stream passed as a join() parameter is indeed a spring proxy instead of proper KStream and that's why it cannot be cast. The logic connected to passing right parameters to testProcessor is probably in KafkaStreamsStreamListenerSetupMethodOrchestrator#adaptAndRetrieveInboundArguments. The logic differs a bit for KStream and KTable (for which joining works). I haven't been able to find any example of joining 2 KStreams, only mix of KStream and KTable.

Any transforms of input2Stream cause it to work, e.g. 
```
KStream<String, TestEvent> other = input2Stream((v) -> v);
```

**Comment by sobychacko** [comment]
@mateuszjadczykDna By the time, your business logic is invoked, the proxy should be replaced with the real `KStream` object. Are you setting the proper Serde's on the inbound configuration? Could you share a small reproducible application where we can see the issue?

**Comment by mateuszjadczykDna** [comment]
@sobychacko All works well if there's only a single input. Here's an example project. If you comment out JoinProcessor and leave only SingleInputProcessor, context loads successfully, both for app and test.
[demo.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/3379017/demo.zip)

**Comment by sobychacko** [comment]
@mateuszjadczykDna This seems to be a bug in the binder. We will fix it and convey what needs to be done. In the meantime, can you work around using the strategy used for joins on this [SO](https://stackoverflow.com/questions/56548736/kstream-kstream-inner-join-throws-java-lang-classcastexception/56551633#56551633) thread? Take a look a the `StreamListener` method - `process1`. It has two `KStream` inputs and does a join, but instead of passing the second `KStream` as it is, it does the join on the actual keys. See if that works for you.

**Comment by sabbyanandan** [comment]
@mateuszjadczykDna: Do you have any thoughts to share on @sobychacko's questions?

**Comment by mateuszjadczykDna** [comment]
TBH, it made more sense in our case to go with just spring-kafka and not use spring-cloud so I didn't test the proposed workaround
