### ISSUE TITLE
Exception after moving to spring 2.1 java.lang.ClassCastException: com.sun.proxy.$Proxy175 cannot be cast to org.apache.kafka.streams.kstream.internals.KStreamImpl

### ISSUE THREAD

**Issue by andriiL1Xsh4nk0** [spring-cloud/spring-cloud-stream-binder-kafka#705]
I had completely working app on spring boot 2.0.5 but after upgrading it to spring boot 2.1.6 it couldn't start. Here is error while starting

> org.springframework.beans.factory.BeanInitializationException: Cannot setup StreamListener for public void com.company.microservice.stream.StreamProcessor.process(org.apache.kafka.streams.kstream.KStream,org.apache.kafka.streams.kstream.KStream); nested exception is java.lang.reflect.InvocationTargetException
        at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.orchestrateStreamListenerSetupMethod(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:214) ~[spring-cloud-stream-binder-kafka-streams-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.doPostProcess(StreamListenerAnnotationBeanPostProcessor.java:226) ~[spring-cloud-stream-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.lambda$postProcessAfterInitialization$0(StreamListenerAnnotationBeanPostProcessor.java:196) ~[spring-cloud-stream-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_201]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.injectAndPostProcessDependencies(StreamListenerAnnotationBeanPostProcessor.java:330) ~[spring-cloud-stream-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(StreamListenerAnnotationBeanPostProcessor.java:113) ~[spring-cloud-stream-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:862) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at com.company.microservice.App.main(App.java:43) [main/:na]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
        at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.orchestrateStreamListenerSetupMethod(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:176) ~[spring-cloud-stream-binder-kafka-streams-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        ... 15 common frames omitted
Caused by: java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy175.join(Unknown Source) ~[na:na]
        at com.company.microservice.stream.StreamProcessor.joinUsersWithData(StreamProcessor.java:84) ~[main/:na]
        at com.company.microservice.stream.StreamProcessor.process(StreamProcessor.java:59) ~[main/:na]
        ... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
        at org.springframework.cloud.stream.binder.kafka.streams.KStreamBoundElementFactory$KStreamWrapperHandler.invoke(KStreamBoundElementFactory.java:103) ~[spring-cloud-stream-binder-kafka-streams-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        ... 23 common frames omitted
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy175 cannot be cast to org.apache.kafka.streams.kstream.internals.KStreamImpl
        at org.apache.kafka.streams.kstream.internals.KStreamImpl.doJoin(KStreamImpl.java:437) ~[kafka-streams-2.0.1.jar:na]
        at org.apache.kafka.streams.kstream.internals.KStreamImpl.join(KStreamImpl.java:407) ~[kafka-streams-2.0.1.jar:na]
        ... 30 common frames omitted

Here is my build.gradle file

```
buildscript {
    ext {
        springBootVersion = '2.1.6.RELEASE'
    }
    ...

plugins {
    ...
    id 'org.springframework.boot' version '2.1.6.RELEASE'
    id 'io.spring.dependency-management' version '1.0.8.RELEASE'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2'
    }
}

dependencies {
...
    compile('org.springframework.cloud:spring-cloud-starter-stream-kafka')
    compile('org.springframework.cloud:spring-cloud-stream-binder-kafka-streams')
    compile('org.apache.kafka:kafka-streams')
    testCompile('org.springframework.boot:spring-boot-starter-test')
    testCompile('org.springframework.kafka:spring-kafka-test:2.1.12.RELEASE')
}
```
for me it looks like some dependency mismatch issue but I'm not sure

**Comment by sabbyanandan** [comment]
Hi, @andriiL1Xsh4nk0. Apologies for the delay. Could you describe the steps as to how you're upgrading to 2.1.x? Did you follow the Spring Initializr route or are you manually upgrading the dependencies? 

The latter is typically the recommended workflow since you will automatically inherit the harmonized _and_ the "compatible" dependencies.

Alternatively, you can build a new app from Spring Initializr and compare the classpath dependencies with your custom app. Other than this, I can't think of any other easier approach to troubleshoot it.

**Comment by sabbyanandan** [comment]
Closing this due to no activity.
