### ISSUE TITLE
package java.net should be included in the DEFAULT_TRUSTED_PACKAGES

### ISSUE THREAD

**Issue by hanishi** [spring-cloud/spring-cloud-stream-binder-kafka#707]
The value for the `Location` key is deserialized as `java.net.URI` but since it is not included in the `DEFAULT_TRUSTED_PACKAGES` following exception is thrown when `DefaultHttpHeaderMapper` tries to handle the message received in its `setHttpHeader` method.

```
java.lang.IllegalArgumentException: Expected URI or String value for 'Location' header value, but received: class org.springframework.cloud.stream.binder.kafka.BinderHeaderMapper$NonTrustedHeaderType
	at org.springframework.integration.http.support.DefaultHttpHeaderMapper.setHttpHeader(DefaultHttpHeaderMapper.java:916) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.integration.http.support.DefaultHttpHeaderMapper.fromHeaders(DefaultHttpHeaderMapper.java:434) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.integration.http.support.DefaultHttpHeaderMapper.fromHeaders(DefaultHttpHeaderMapper.java:74) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.integration.http.inbound.HttpRequestHandlingEndpointSupport.setupResponseAndConvertReply(HttpRequestHandlingEndpointSupport.java:407) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]

```

**Comment by artembilan** [comment]
I think this must go to the Spring for Apache Kafka as well. 
There is that `DefaultKafkaHeaderMapper` with `DEFAULT_TRUSTED_PACKAGES`, so this `java.net` should be included there.
This Binder will pick the change up smoothly afterward and that `Location` header will be mapped properly.
Meanwhile you can use `spring.cloud.stream.kafka.binder.headerMapperBeanName` to provide your custom `DefaultKafkaHeaderMapper` bean with additional `trsutedPackages`: https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_configuration_options_2

Please, move this issue into https://github.com/spring-projects/spring-kafka

**Comment by hanishi** [comment]
moved this issue to https://github.com/spring-projects/spring-kafka/issues/1176
