### ISSUE TITLE
Spring Cloud Stream Kafka Producer ERROR - no subscribers for channel

### ISSUE THREAD

**Issue by tjjosep** [spring-cloud/spring-cloud-stream-binder-kafka#733]
If I run it from local host this is working But if I deploy to PCF with same config I getting the error.

**Test on Local host**

`$ curl -k -X POST -H "Content-Type: application/json" -d '{"name": "XXX xxx", "zipcode": "99999"}' http://localhost:8080/kafka/event/trigger/
`
Respose
`
Inquiry Sent
`

**But I sent perform the same test on PCF I get error as below**

`$ curl -k -X POST -H "Content-Type: application/json" -d '{"name": "XX XXX", "zipcode": "9999"}' https://remoteserver.org/kafka/event/trigger/

`
Response

```json
{"timestamp":"2019-09-03T01:20:46.440+0000","status":500,"error":"Internal Server Error","message":"Dispatcher has no subscribers for channel 'application.output'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[71], headers={contentType=application/json, id=cedc509e-2cbd-1916-031f-865c29bdc5dd, timestamp=1567473646438}]","path":"/kafka/event/trigger/"}
```

***PCF Log***
```bash
  2019-09-02T20:20:46.43-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:20:46.437 - INFO 17 --- [nio-8080-exec-3] s.c.k.s.b.e.t.ProducerService            : Online Inquiry=Inquiry{zipcode='99999', name='xxx xx'}
   2019-09-02T20:20:46.43-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:20:46.439 -ERROR 17 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.output'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[71], headers={contentType=application/json, id=cedc509e-2cbd-1916-031f-865c29bdc5dd, timestamp=1567473646438}], failedMessage=GenericMessage [payload=byte[71], headers={contentType=application/json, id=cedc509e-2cbd-1916-031f-865c29bdc5dd, timestamp=1567473646438}]] with root cause
   2019-09-02T20:20:46.43-0500 [APP/PROC/WEB/0] OUT org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers 	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:138) 	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105) 	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401) 	at sf.cloudnative.kafka.springcloud.binder.example.transactionproducer.ProducerService.produce(ProducerService.java:24) 	at sf.cloudnative.kafka.springcloud.binder.example.transactionproducer.Controller.trigger(Controller.java:24) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114) 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.lang.Thread.run(Thread.java:748) 
   2019-09-02T20:21:26.90-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:21:26.901 - WARN 17 --- [ adminclient-23] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-23] Connection to node 2 could not be established. Broker may not be available.
   2019-09-02T20:21:26.90-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:21:26.902 -ERROR 17 --- [ask-scheduler-9] o.s.cloud.stream.binding.BindingService  : Failed to create producer binding; retrying in 30 seconds
   2019-09-02T20:21:26.90-0500 [APP/PROC/WEB/0] OUT org.springframework.cloud.stream.provisioning.ProvisioningException: Provisioning exception; nested exception is java.util.concurrent.TimeoutException 	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopic(KafkaTopicProvisioner.java:290) 	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:137) 	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:78) 	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:193) 	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:97) 	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:151) 	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleProducerBinding$2(BindingService.java:290) 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.util.concurrent.TimeoutException: null 	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108) 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:274) 	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopicAndPartitions(KafkaTopicProvisioner.java:323) 	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopicIfNecessary(KafkaTopicProvisioner.java:299) 	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopic(KafkaTopicProvisioner.java:281) 	... 14 common frames omitted 
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:21:56.903 - INFO 17 --- [ask-scheduler-9] o.s.c.s.b.k.p.KafkaTopicProvisioner      : Using kafka topic for outbound: inquiry.topic
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:21:56.903 - INFO 17 --- [ask-scheduler-9] o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values:
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	bootstrap.servers = [xx.xxx.xxx.xx:31099]
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	client.id =
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	connections.max.idle.ms = 300000
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	metadata.max.age.ms = 300000
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	metric.reporters = []
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	metrics.num.samples = 2
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	metrics.recording.level = INFO
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	metrics.sample.window.ms = 30000
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	receive.buffer.bytes = 65536
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	reconnect.backoff.max.ms = 1000
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	reconnect.backoff.ms = 50
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	request.timeout.ms = 120000
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	retries = 5
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	retry.backoff.ms = 100
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.client.callback.handler.class = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.jaas.config = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.kerberos.min.time.before.relogin = 60000
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.kerberos.service.name = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.kerberos.ticket.renew.jitter = 0.05
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.kerberos.ticket.renew.window.factor = 0.8
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.login.callback.handler.class = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.login.class = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.login.refresh.buffer.seconds = 300
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.login.refresh.min.period.seconds = 60
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.login.refresh.window.factor = 0.8
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.login.refresh.window.jitter = 0.05
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	sasl.mechanism = GSSAPI
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	security.protocol = PLAINTEXT
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	send.buffer.bytes = 131072
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.cipher.suites = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.endpoint.identification.algorithm = https
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.key.password = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.keymanager.algorithm = SunX509
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.keystore.location = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.keystore.password = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.keystore.type = JKS
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.protocol = TLS
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.provider = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.secure.random.implementation = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.trustmanager.algorithm = PKIX
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.truststore.location = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.truststore.password = null
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT 	ssl.truststore.type = JKS
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:21:56.904 - INFO 17 --- [ask-scheduler-9] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 2.0.1
   2019-09-02T20:21:56.90-0500 [APP/PROC/WEB/0] OUT --2019-09-03 01:21:56.904 - INFO 17 --- [ask-scheduler-9] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : fa14705e51bd2ce5
```

**This is the POM**

	`<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.7.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>cloudnative.kafka.springcloud.binder.example</groupId>
	<artifactId>kafka-transaction-producer</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>kafka-transaction-producer</name>
	<description>Demo project for Spring cloud stream kafka transaction producer</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Greenwich.SR2</spring-cloud.version>
		<spring-cloud-services.version>2.1.4.RELEASE</spring-cloud-services.version>
		
	</properties>
  
       <dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.pivotal.spring.cloud</groupId>
				<artifactId>spring-cloud-services-dependencies</artifactId>
				<version>${spring-cloud-services.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-dependencies</artifactId>
			<version>${spring-cloud-stream.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>build-info</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
			</plugin>
		</plugins>
	</build>`

**This my main**

`
@SpringBootApplication
public class TransactionProducerApplication {

	public static void main(String[] args) {
		SpringApplication.run(TransactionProducerApplication.class, args);
	}

}
`

**ProducerConfig**

`
@Configuration
@AutoConfigureBefore(BindingServiceConfiguration.class)
@EnableBinding({Source.class})
public class ProducerConfig {

    private final Logger logger = LoggerFactory.getLogger(this.getClass().getName());

    private Source source;

    public ProducerConfig(Source source) {
       this.source = source;
    }

    public Source getSource() {
        return source;
    }

    public void setSource(Source source) {
        this.source = source;
    }

}
`

**ProducerService**

`
@Service
public class ProducerService {

    private final Logger logger = LoggerFactory.getLogger(this.getClass().getName());

    @Autowired
    ProducerConfig producer;

    String produce(Inquiry inquiry) {
        logger.info("Online Inquiry={}", inquiry);

        InquiryEvent inquiryEvent = new InquiryEvent();
        inquiryEvent.setType("CreateInquiry");
        inquiryEvent.setInquiry(inquiry);

        producer.getSource().output().send(MessageBuilder.withPayload(inquiryEvent).build());
        logger.info("Produced Inquiry Event={}", inquiryEvent);

        return "Inquiry Sent";
    }

}
`

**Controller**

`@RestController
@RequestMapping(value = "/kafka/event")
public class Controller {

    private final Logger logger = LoggerFactory.getLogger(this.getClass().getName());

    @Autowired
    ProducerService producerService;

    @PostMapping(value = "/trigger")
    public String trigger(@RequestBody Inquiry inquiry) {

        return producerService.produce(inquiry);

    }
}`

**Application.yml**

```YAML
spring:
  profiles: PCF #29 
  cloud:
    stream:
      bindings:
        output:
          binder: kafka1
          destination: inquiry.topic
          contentType: application/json
          producer:
            partitionCount: 1
      binders:
        kafka1:
          type: kafka
          environment.spring.cloud.stream.kafka:
            binder:
              brokers: xx.xxx.xxx.xx
              defaultBrokerPort: 31099
              autoAddPartitions: true`

**Comment by tjjosep** [comment]
Thank you Jim, you are correct. We realized the broker IP we had the firewall rule was rescheduled by Kubernates. Trying to use a MetaLB IP so that it will be same for rescheduled containers as well.
____________
Looks like trouble creating the connection. Is an Application Security Group (ASG) in place on that foundation to allow outbound connectivity from app instances to Kafka? Could be a firewall rule too.
 
Jim Basler | Pivotal
