### ISSUE TITLE
Authentication error even when JAAS is disabled

### ISSUE THREAD

**Issue by boonware** [spring-cloud/spring-cloud-stream-binder-kafka#764]
# Background
I have an application using Spring Cloud Stream plain Kafka binder and also the Streams binder (latest release). I am connecting to Event Streams on IBM Cloud, and also for local development I am connecting to Kafka containers (https://github.com/bitnami/bitnami-docker-kafka).

# Problem
For local development I want to disable JAAS authentication, which is required for Event Streams connection. This is my properties file:

```
spring.cloud.stream.bindings.input.destination = inputTopic
spring.cloud.stream.bindings.input.group = inputGroup
spring.cloud.stream.bindings.input.contentType: application/json
 
spring.cloud.stream.kafka.streams.binder.brokers = ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde = org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde = org.apache.kafka.common.serialization.Serdes$StringSerde

# IBM Cloud Event Streams authentication & security
spring.kafka.jaas.enabled = ${KAFKA_JAAS_ENABLED:false}
spring.kafka.jaas.options.username = ${KAFKA_JAAS_USERNAME}
spring.kafka.jaas.options.password = ${KAFKA_JAAS_PASSWORD}
spring.kafka.jaas.login-module = org.apache.kafka.common.security.plain.PlainLoginModule
spring.kafka.properties.security.protocol = SASL_SSL
spring.kafka.properties.sasl.mechanism = PLAIN
spring.kafka.properties.ssl.protocol = TLSv1.2
spring.kafka.properties.ssl.enabled.protocols = TLSv1.2
spring.kafka.bootstrap-servers = ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Further tweaks required for IBM Cloud Event Streams
spring.kafka.streams.replication-factor = ${KAFKA_STREAMS_REPLICATION_FACTOR:3} 
topic.retention.ms = ${KAFKA_TOPIC_RETENTION_MS:86400000} 

# Spring Cloud Stream Kafka binder
spring.cloud.stream.kafka.binder.brokers =${spring.kafka.bootstrap-servers}
spring.cloud.stream.kafka.binder.autoCreateTopics = true
spring.cloud.stream.kafka.bindings.input.consumer.enableDlq = true
spring.cloud.stream.kafka.bindings.input.consumer.dlq-name = dlqTopic
```

When running locally if I set `spring.kafka.jaas.enabled = true` but don't set the environment variables for username and password I get the following:

> org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node -1 terminated during authentication. This may indicate that authentication failed due to invalid credentials.

So far so good, I just need to disable JAAS and I can connect without authentication, right? So I set `spring.kafka.jaas.enabled = false` and now I get the error shown below.

The configuration above works when connecting to Event Streams, but **fails even when JAAS is disabled** when trying to connect to the local cluster. If I **remove** ALL of the configuration properties for connecting to Event Streams then I can connect once again to the local Kafka.

# Full Stack Trace
> org.springframework.context.ApplicationContextException: Failed to start bean 'streamsBuilderFactoryManager'; nested exception is org.springframework.kafka.KafkaException: Could not start stream: ; nested exception is org.springframework.kafka.KafkaException: Could not start stream: ; nested exception is org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
> 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at com.ibm.tcp.exploder.ApplicationBootstrap.main(ApplicationBootstrap.java:30) [classes!/:0.1.0-dev.21.uncommitted+story.54.3.85c86b1]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [exploder-service-0.1.0-dev.21.uncommitted+story.54.3.85c86b1.jar:0.1.0-dev.21.uncommitted+story.54.3.85c86b1]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [exploder-service-0.1.0-dev.21.uncommitted+story.54.3.85c86b1.jar:0.1.0-dev.21.uncommitted+story.54.3.85c86b1]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [exploder-service-0.1.0-dev.21.uncommitted+story.54.3.85c86b1.jar:0.1.0-dev.21.uncommitted+story.54.3.85c86b1]
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [exploder-service-0.1.0-dev.21.uncommitted+story.54.3.85c86b1.jar:0.1.0-dev.21.uncommitted+story.54.3.85c86b1]
> Caused by: org.springframework.kafka.KafkaException: Could not start stream: ; nested exception is org.springframework.kafka.KafkaException: Could not start stream: ; nested exception is org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
> 	at org.springframework.cloud.stream.binder.kafka.streams.StreamsBuilderFactoryManager.start(StreamsBuilderFactoryManager.java:76) ~[spring-cloud-stream-binder-kafka-streams-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
> 	... 22 common frames omitted
> Caused by: org.springframework.kafka.KafkaException: Could not start stream: ; nested exception is org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
> 	at org.springframework.kafka.config.StreamsBuilderFactoryBean.start(StreamsBuilderFactoryBean.java:312) ~[spring-kafka-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
> 	at org.springframework.cloud.stream.binder.kafka.streams.StreamsBuilderFactoryManager.start(StreamsBuilderFactoryManager.java:70) ~[spring-cloud-stream-binder-kafka-streams-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
> 	... 23 common frames omitted
> Caused by: org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
> 	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:370) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:62) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier.getAdminClient(DefaultKafkaClientSupplier.java:34) ~[kafka-streams-2.0.1.jar!/:na]
> 	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:707) ~[kafka-streams-2.0.1.jar!/:na]
> 	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:556) ~[kafka-streams-2.0.1.jar!/:na]
> 	at org.springframework.kafka.config.StreamsBuilderFactoryBean.start(StreamsBuilderFactoryBean.java:294) ~[spring-kafka-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
> 	... 24 common frames omitted
> Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: KrbException: Cannot locate default realm
> 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:153) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:140) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:346) ~[kafka-clients-2.0.1.jar!/:na]
> 	... 29 common frames omitted
> Caused by: javax.security.auth.login.LoginException: KrbException: Cannot locate default realm
> 	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:804) ~[na:1.8.0_201]
> 	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617) ~[na:1.8.0_201]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
> 	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[na:1.8.0_201]
> 	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[na:1.8.0_201]
> 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[na:1.8.0_201]
> 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[na:1.8.0_201]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_201]
> 	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[na:1.8.0_201]
> 	at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[na:1.8.0_201]
> 	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:64) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:114) ~[kafka-clients-2.0.1.jar!/:na]
> 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:142) ~[kafka-clients-2.0.1.jar!/:na]
> 	... 33 common frames omitted
> Caused by: sun.security.krb5.RealmException: KrbException: Cannot locate default realm
> 	at sun.security.krb5.Realm.getDefault(Realm.java:68) ~[na:1.8.0_201]
> 	at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:462) ~[na:1.8.0_201]
> 	at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:471) ~[na:1.8.0_201]
> 	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:706) ~[na:1.8.0_201]
> 	... 49 common frames omitted
> Caused by: sun.security.krb5.KrbException: Cannot locate default realm
> 	at sun.security.krb5.Config.getDefaultRealm(Config.java:1029) ~[na:1.8.0_201]
> 	at sun.security.krb5.Realm.getDefault(Realm.java:64) ~[na:1.8.0_201]
> 	... 52 common frames omitted

**Comment by boonware** [comment]
OK, I spent some more time digging and then I realized that `spring.kafka.properties.security.protocol = PLAINTEXT` is also required. It is not sufficient to simply disable JAAS. Hopefully someone else may find this useful.
