### ISSUE TITLE
Spring cloud stream producer and consumer unable to create Topic and Partitions  in Confluent Kafka

### ISSUE THREAD

**Issue by suresh-chidham** [spring-cloud/spring-cloud-stream-binder-kafka#822]
Hi
We configured below  kafka binder and boot properties
1) spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers={confluent_hostname:port}
2) spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.configuration.sasl.mechanism=PLAIN
3)spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.configuration.security.protocol=SASL_SSL
4)spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.jaas.loginModule=org.apache.kafka.common.security.plain.PlainLoginModule
5) spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.jaas.options.password=confluent-api-secret
6)spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.jaas.options.username=confluent-api-key
7) spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.replicationFactor=3
8)=spring.cloud.dataflow.applicationProperties.stream.spring.kafka.consumer.keyDeserializer=org.apache.kafka.common.serialization.StringDeserializer
9)spring.cloud.dataflow.applicationProperties.stream.spring.kafka.consumer.valueDeserializer=org.apache.kafka.common.serialization.StringDeserializer

and few other consumer properties also

I have created sample producer and consumer  streams and deployed in Spring cloud data flow server in PCF environment
1) stream create SCDF_triggerIngest --definition "http > :test_topic"  
2) stream create SCDF_ingestFileNames --definition ":test_topic > router --expression='#jsonPath(payload, '$.tspName')' "

We are getting below error for every 30 seconds in  http (producer) 

2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] bootstrap.servers = [**confluent_hostname:port**]
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] client.id =
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] connections.max.idle.ms = 300000
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] metadata.max.age.ms = 300000
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] metric.reporters = []
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] metrics.num.samples = 2
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] metrics.recording.level = INFO
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] metrics.sample.window.ms = 30000
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] receive.buffer.bytes = 65536
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] reconnect.backoff.max.ms = 1000
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] reconnect.backoff.ms = 50
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] request.timeout.ms = 120000
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] retries = 5
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] retry.backoff.ms = 100
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.client.callback.handler.class = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.jaas.config = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.kerberos.kinit.cmd = /usr/bin/kinit
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.kerberos.min.time.before.relogin = 60000
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.kerberos.service.name = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.kerberos.ticket.renew.jitter = 0.05
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.kerberos.ticket.renew.window.factor = 0.8
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.login.callback.handler.class = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.login.class = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.login.refresh.buffer.seconds = 300
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.login.refresh.min.period.seconds = 60
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.login.refresh.window.factor = 0.8
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.login.refresh.window.jitter = 0.05
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] sasl.mechanism = PLAIN
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] security.protocol = SASL_SSL
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] send.buffer.bytes = 131072
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.cipher.suites = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.endpoint.identification.algorithm = https
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.key.password = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.keymanager.algorithm = SunX509
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.keystore.location = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.keystore.password = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.keystore.type = JKS
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.protocol = TLS
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.provider = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.secure.random.implementation = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.trustmanager.algorithm = PKIX
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.truststore.location = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.truststore.password = null
2019-12-18T18:12:46.801+05:30 [APP/PROC/WEB/0] [OUT] ssl.truststore.type = JKS
2019-12-18T18:12:46.855+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:42:46.855 INFO 22 --- [ main] o.a.k.c.s.authenticator.AbstractLogin : Successfully logged in.
2019-12-18T18:12:46.935+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:42:46.934 INFO 22 --- [ main] ContainerTrustManagerFactory$PKIXFactory : Adding System Trust Manager
2019-12-18T18:12:46.935+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:42:46.935 INFO 22 --- [ main] ContainerTrustManagerFactory$PKIXFactory : Adding TrustManager for /etc/ssl/certs/ca-certificates.crt
2019-12-18T18:12:46.938+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:42:46.938 INFO 22 --- [tificates.crt-0] org.cloudfoundry.security.FileWatcher : Start watching /etc/ssl/certs/ca-certificates.crt
2019-12-18T18:12:47.059+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:42:47.058 INFO 22 --- [ main] c.s.FileWatchingX509ExtendedTrustManager : Initialized TrustManager for /etc/ssl/certs/ca-certificates.crt
2019-12-18T18:12:47.092+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:42:47.092 INFO 22 --- [ main] o.a.kafka.common.utils.AppInfoParser : Kafka version : 2.0.1
2019-12-18T18:12:47.092+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:42:47.092 INFO 22 --- [ main] o.a.kafka.common.utils.AppInfoParser : Kafka commitId : fa14705e51bd2ce5
2019-12-18T18:13:11.140+05:30 [RTR/2] [OUT] scdf_triggeringest-http-v10.acp.ptlapps.com - [2019-12-18T12:43:11.137+0000] "OPTIONS /cloudfoundryapplication HTTP/1.1" 502 0 67 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36" "10.50.54.216:45898" "10.50.52.153:61074" x_forwarded_for:"3.147.210.55, 10.50.54.216" x_forwarded_proto:"https" vcap_request_id:"dc4fb795-f746-431e-5ab3-652a3a5b2c04" response_time:0.002853096 app_id:"8faebc93-8b34-40fc-8829-61a7c43b988d" app_index:"0" x_b3_traceid:"4a14ed634414fc66" x_b3_spanid:"4a14ed634414fc66" x_b3_parentspanid:"-" b3:"4a14ed634414fc66-4a14ed634414fc66"
2019-12-18T18:14:46.450+05:30 [APP/PROC/WEB/1] [OUT] 2019-12-18 12:44:46.449 INFO 21 --- [| adminclient-1] o.a.k.c.a.i.AdminMetadataManager : [AdminClient clientId=adminclient-1] Metadata update failed
2019-12-18T18:14:46.450+05:30 [APP/PROC/WEB/1] [OUT] org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
2019-12-18T18:14:47.098+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:44:47.098 INFO 22 --- [| adminclient-1] o.a.k.c.a.i.AdminMetadataManager : [AdminClient clientId=adminclient-1] Metadata update failed
2019-12-18T18:14:47.098+05:30 [APP/PROC/WEB/0] [OUT] org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
2019-12-18T18:14:56.735+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:44:56.735 WARN 22 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient : [AdminClient clientId=adminclient-1] Connection to node -1 could not be established. Broker may not be available.
2019-12-18T18:14:56.736+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:44:56.735 INFO 22 --- [| adminclient-1] o.a.k.c.a.i.AdminMetadataManager : [AdminClient clientId=adminclient-1] Metadata update failed
2019-12-18T18:14:56.736+05:30 [APP/PROC/WEB/0] [OUT] org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited.
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] 2019-12-18 12:44:56.740 ERROR 22 --- [ main] o.s.cloud.stream.binding.BindingService : Failed to create producer binding; retrying in 30 seconds
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] org.springframework.cloud.stream.provisioning.ProvisioningException: Provisioning exception; nested exception is java.util.concurrent.TimeoutException
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopic(KafkaTopicProvisioner.java:290) ~[spring-cloud-stream-binder-kafka-core-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:137) ~[spring-cloud-stream-binder-kafka-core-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:78) ~[spring-cloud-stream-binder-kafka-core-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:193) ~[spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:97) ~[spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:151) ~[spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binding.BindingService.doBindProducer(BindingService.java:268) [spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:243) [spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindOutputs(BindableProxyFactory.java:287) [spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:58) [spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_222]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:48) ~[spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34) [spring-cloud-stream-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
2019-12-18T18:14:56.741+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]

Similarly we are getting error for router(consumer)
When I go through error stack-trace, AdminClient is trying to get listOfTopic, we are getting Timeout error. 
Please can you help on this?

**Comment by sobychacko** [comment]
@suresh-chidham Could it be that there are some connectivity issues to your Kafka environment? Or you are running against a restricted Kafka cluster or that the security credentials that you are passing are wrong? It might be worthwhile to create a standalone Spring Cloud Stream application and trying to connect to your Kafka cluster to rule out any issues with the communication to Kafka.

**Comment by sabbyanandan** [comment]
Closing due to no activity.
