### ISSUE TITLE
Functional binding is disabled due to the presense of @EnableBinding annotation in your configuration

### ISSUE THREAD

**Issue by NandAtTSB** [spring-cloud/spring-cloud-stream-binder-kafka#882]
I  have a MQTT client which receives messages from MQTT broker and then publishes those messages to Kafka topic for which I created a @output channel so I had to  @Enablebinding.
In the same Spring boot application I have a stream processor which processes KStream.
Here's the snippet
public class ProcessMessagesFromKafka{
@Bean
public Consumer<KStream<String, SpecificRecordBase>> processAndPublish() {}
}
In 
@EnableBinding(CollectChannels.class)
public class MqttAsyncCallback {
       @Override
	public void messageArrived(String topic, MqttMessage message) throws Exception {
		log.info("received message, topic:{}, message:{}", topic, message);
		String jsonPayload = new String(message.getPayload());
		collectChannels.collect().send(buildAvroPayload(jsonPayload));
	}
}

This works perfectly fine you can see I am using functional style approach. But the moment I try to add another Bean say 
@Bean
public Consumer<KStream<String, SpecificRecordBase>> processStream () {}
}
and application.yml
I defined 
spring.cloud.function.definition: processAndPublish, processStream

Spring complains:
INFO 25619 --- [           main] onConfiguration$FunctionBindingRegistrar : Functional binding is disabled due to the presense of @EnableBinding annotation in your configuration

java.lang.IllegalStateException: Multiple functions found, but function definition property is not set.
	at org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsFunctionBeanPostProcessor.extractResolvableTypes(KafkaStreamsFunctionBeanPostProcessor.java:124) ~[spring-cloud-stream-binder-kafka-streams-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
	at org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsFunctionBeanPostProcessor.afterPropertiesSet(KafkaStreamsFunctionBeanPostProcessor.java:90) ~[spring-cloud-stream-binder-kafka-streams-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:539) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at com.tsb.cb.MqttConnectorApplication.main(MqttConnectorApplication.java:21) ~[classes/:na]

**Comment by sobychacko** [comment]
I noticed that you have this in your configuration: `spring.cloud.function.definition: processAndPublish, processStream`.
It needs to be: `spring.cloud.function.definition: processAndPublish;processStream`. Wonder if that is the issue?

**Comment by NandAtTSB** [comment]
Thanks for quick response no that's not the issue because I have been using comma in my other applications and they all work fine.

**Comment by NandAtTSB** [comment]
> I noticed that you have this in your configuration: `spring.cloud.function.definition: processAndPublish, processStream`.
> It needs to be: `spring.cloud.function.definition: processAndPublish;processStream`. Note the semicolon separating the functions. Wonder if that is the issue?
Thanks for quick response no that's not the issue because I have been using comma in my other applications and they all work fine.

**Comment by sobychacko** [comment]
@NandAtTSB In that case, any chance you can share with us a small sample app where we can reproduce what you are facing?

**Comment by NandAtTSB** [comment]
@sobychacko cool I'll try to make one.

**Comment by sabbyanandan** [comment]
Closing due to no activity.

**Comment by davidwadden** [comment]
@sobychacko I'm running into this one too trying to evolve an `@EnableBinding`-configured application to the functional bean declarations (since apparently `@StreamListener` is set to be deprecated).  I'd ideally like to leverage functional definitions alongside the existing channel definitions via `@EnableBinding`.  I'm seeing the the same in my log at startup (traced to [`FunctionConfiguration.java:665`](https://github.com/spring-cloud/spring-cloud-stream/blob/v3.0.2.RELEASE/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L665))

```
11:25:50.145 [Test worker] INFO  o.s.c.s.f.FunctionConfiguration$FunctionBindingRegistrar - Functional binding is disabled due to the presense of @EnableBinding annotation in your configuration
```

Is there any way to use SCSt functional processors alongside `@EnableBinding` ?  I've also got the challenge of adapting from an inbound REST Controller to publishing using the `Supplier` interface to make a Source of some sort.  The examples use a `BlockingQueue` and the supplier polls the queue, is this going to get polled using the 1Hz defaultPoller (I believe?) ?

**Comment by CKFVL** [comment]
Has this been resolved? I am facing this issue when upgrading spring boot to 2.3.0.RELEASE and the application is stuck at starting and it never starts.

**Comment by sobychacko** [comment]
@CKFVL This repository has been migrated to the core [Spring Cloud Stream](https://github.com/spring-cloud/spring-cloud-stream). Please open a new issue in the core repository with enough context to triage the issue further.
