### ISSUE TITLE
Dlq error handling not working in TransformerSupplier for Avro Messages

### ISSUE THREAD

**Issue by NandAtTSB** [spring-cloud/spring-cloud-stream-binder-kafka#886]
As per the sample application  https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-dlq-sample
I in my application followed the same pattern the only difference is it's using AvroMessage and in the Kafka Tranformer I am checking some header value and throwing an exception but I can't see a firstly a error topic getting created nor the message is routed to the dlq
Below is the code and the stacktrace:

```yaml
spring.cloud.stream:
  function.definition: processor 
  # Kafka config
  kafka.streams.binder:
        applicationId: instruct
        configuration.schema.registry.url: http://localhost:8081
        configuration.default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        configuration.default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        serdeError: sendToDlq
 bindings:
    processor-in-0:
        destination: topicA
     processor-out-0:
        destination: topicB
     processor-out-1:
        destination: topicC
  
  kafka.streams.bindings.processor-in-0.consumer:
     dlqName: error.topicA
     value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
```
And my 

```java
package com.tsb.cb.stream.processor;

import static com.tsb.cb.stream.processor.ProcessorUtil.CORRELATION_ID;
import static com.tsb.cb.stream.processor.ProcessorUtil.SCA_INSTRUCT_STORE;

import org.apache.avro.specific.SpecificRecordBase;
import org.apache.kafka.common.header.Header;
import org.apache.kafka.streams.KeyValue;
import org.apache.kafka.streams.kstream.Transformer;
import org.apache.kafka.streams.processor.ProcessorContext;
import org.apache.kafka.streams.state.SessionStore;

import com.tsb.cb.exception.ScaInvalidRecordException;
import com.tsb.cb.stream.schema.Customer;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ScaInstructTransformer implements Transformer<String, Customer, KeyValue<String, SpecificRecordBase>> {
	private ProcessorContext context;
	private SessionStore<String, SpecificRecordBase> stateStore;

	@SuppressWarnings("unchecked")
	@Override
	public void init(ProcessorContext context) {
		this.context = context;
		stateStore = (SessionStore<String, SpecificRecordBase>) context.getStateStore(STORE);
	}

	@Override
	public KeyValue<String, SpecificRecordBase> transform(final String key, final Customer value) {
		final Header correlationId = this.context.headers().lastHeader(CORRELATION_ID);
		if(correlationId == null || correlationId.value() == null) {
			throw new ScaInvalidRecordException("CorrelationId missing in the header");
		}
		return KeyValue.pair(key, value);
	}
	@Override
	public void close() {
		this.stateStore.close();
	}
}
```
================================================================

```
2020-04-28 19:49:23.203  INFO 26469 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf-StreamThread-1] State transition from RUNNING to PENDING_SHUTDOWN
2020-04-28 19:49:23.203  INFO 26469 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf-StreamThread-1] Shutting down
2020-04-28 19:49:23.219  INFO 26469 --- [-StreamThread-1] o.a.k.clients.consumer.KafkaConsumer     : [Consumer clientId=customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf-StreamThread-1-restore-consumer, groupId=null] Unsubscribed all topics or patterns and assigned partitions
2020-04-28 19:49:23.219  INFO 26469 --- [-StreamThread-1] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf-StreamThread-1-producer] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2020-04-28 19:49:23.243  INFO 26469 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf-StreamThread-1] State transition from PENDING_SHUTDOWN to DEAD
Exception in thread "customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf-StreamThread-1" 2020-04-28 19:49:23.244  INFO 26469 --- [-StreamThread-1] org.apache.kafka.streams.KafkaStreams    : stream-client [customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf] State transition from RUNNING to ERROR
2020-04-28 19:49:23.244 ERROR 26469 --- [-StreamThread-1] org.apache.kafka.streams.KafkaStreams    : stream-client [customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf] All stream threads have died. The instance will be in error state and should be closed.
2020-04-28 19:49:23.244  INFO 26469 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [customerLookupResponseProcessor-applicationId-4ee2f4bf-3248-4435-a3d2-d04eead78dcf-StreamThread-1] Shutdown complete
com.tsb.cb.exception.ScaInvalidRecordException: CorrelationId missing in the header
	at com.tsb.cb.stream.processor.ScaInstructTransformer.transform(ScaInstructTransformer.java:35)
	at com.tsb.cb.stream.processor.ScaInstructTransformer.transform(ScaInstructTransformer.java:1)
	at org.apache.kafka.streams.kstream.internals.TransformerSupplierAdapter$1.transform(TransformerSupplierAdapter.java:47)
	at org.apache.kafka.streams.kstream.internals.TransformerSupplierAdapter$1.transform(TransformerSupplierAdapter.java:36)
	at org.apache.kafka.streams.kstream.internals.KStreamFlatTransform$KStreamFlatTransformProcessor.process(KStreamFlatTransform.java:56)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamPassThrough$KStreamPassThroughProcessor.process(KStreamPassThrough.java:33)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:188)
	at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:48)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:87)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:363)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:199)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:425)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:912)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:819)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:788)
```

**Comment by sobychacko** [comment]
@NandAtTSB Apologies for the delay in responding. I was able to take a look at this. The DLQ support in the Kafka Streams binder is limited to deserialization errors only. This means that, if the binder detects an error from deserialization, it allows you to send the record in error to a DLQ destination. Any other errors within the application, as demonstrated in the code you provided above, must be handled by the application itself. The binder does not give a direct way to handle those. You can, however, catch that exception within your logic and send explicitly to the DLQ topic (for e.g using `KafkaTemplate` from Spring Kafka and calls `send`). If you do that, make sure that you don't throw an exception from the application, as that will stop the Kafka Streams task and thus the application. The record will be committed and the main consumer offset will move forward. I am surprised that you did not see the DLQ topic gets created. It should have created by the binder provisioned. I just tried an app on my end and saw that the DLQ topic was created. Can you set a breakpoint [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderUtils.java#L74)? and [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderUtils.java#L85)? And make sure that the DLQ topic creation code gets activated. 
Once again, unless your deserializer throws some exceptions, the Kafka Streams binder provided DLQ support will not do anything, it is on the application to handle that explicitly. Hope this helps.

**Comment by NandAtTSB** [comment]
Many thanks for your detailed explanation, I'll keep in mind the suggested approach going forward.
