### ISSUE TITLE
batch-mode doesn't work when using 3.x

### ISSUE THREAD

**Issue by AlvinYueChao** [spring-cloud/spring-cloud-stream-binder-kafka#892]
as mentioned in the README, 

>Starting with version 3.0, when spring.cloud.stream.binding.<name>.consumer.batch-mode is set to true, all of the records received by polling the Kafka Consumer will be presented as a List<?> to the listener method. Otherwise, the method will be called with one record at a time. The size of the batch is controlled by Kafka consumer properties max.poll.records, min.fetch.bytes, fetch.max.wait.ms; refer to the Kafka documentation for more information.`

but when I use `org.springframework.cloud:spring-cloud-stream-binder-kafka:3.0.4.RELEASE`, it still doesn't work.
When I try to use `List<T>` in listener, I got the below error messages:
```
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binding.StreamListenerMessageHandler@656f62dc]; nested exception is org.springframework.messaging.converter.MessageConversionException: Cannot parse payload ; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of START_OBJECT token
 at [Source: (String)"{"id":3205795182502117669,"location":"ShangHai","ownerName":"Tina","publishedTime":"2020-05-13T07:52:31.960Z"}"; line: 1, column: 1], failedMessage=GenericMessage [payload={"id":3205795182502117669,"location":"ShangHai","ownerName":"Tina","publishedTime":"2020-05-13T07:52:31.960Z"}, headers={kafka_offset=8, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@35b7e9aa, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=null, kafka_receivedPartitionId=1, kafka_receivedTopic=org.example.alvin.spring.cloud.kafka.input, kafka_receivedTimestamp=1589356373714, contentType=application/json, kafka_groupId=receive-in-group-1}]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:1790) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1779) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1692) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1618) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1521) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1262) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1009) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:929) [spring-kafka-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_211]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
```

the below is part of my configuration in `application.yml`
```yaml
spring:
    cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.20.10:9092
          zkNodes: 192.168.20.10:2181
          autoCreateTopics: false
          configuration:
            security.protocol: PLAINTEXT
            sasl.mechanism: PLAIN
        bindings:
          kafka-in-0:
            consumer:
              batch-mode: true
              configuration:
                auto.offset.reset: earliest
                group.id: receive-in-group-1
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          kafka-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        kafka-in-0:
          binder: kafka
          destination: org.example.alvin.spring.cloud.kafka.input
          contentType: application/json
        kafka-out-0:
          binder: kafka
          destination: org.example.alvin.spring.cloud.kafka.output
          contentType: application/json
```

**Comment by garyrussell** [comment]
Please read up on GitHub markdown.

>`doInvokeRecordListener`

`batch-mode` is a common consumer binding property; you have specified it as a kafka-specific consumer property.

Bear in mind that batch mode is not supported with `@StreamListener` - it only works with the newer functional programming model.

**Comment by AlvinYueChao** [comment]
@garyrussell Thanks for your answer，could you please give me a simple demo so that I can get more
details for the newer listener mode in 3.x

**Comment by garyrussell** [comment]
```java
@SpringBootApplication
public class Kbgh892Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh892Application.class, args);
	}

	@Bean
	Consumer<List<byte[]>> input() {
		return list -> {
			System.out.println(list);
		};
	}

	@Bean
	public ApplicationRunner runner(KafkaTemplate<byte[], byte[]> template) {
		return args -> {
			template.send("kbgh892", "foo".getBytes());
			template.send("kbgh892", "bar".getBytes());
		};
	}

}
```

```properties
spring.kafka.producer.properties.linger.ms=50

spring.cloud.stream.bindings.input-in-0.consumer.batch-mode=true
spring.cloud.stream.bindings.input-in-0.group=kbgh892
spring.cloud.stream.bindings.input-in-0.destination=kbgh892
spring.cloud.stream.bindings.input-in-0.content-type=text/plain
```

Note: there is currently no automatic payload conversion ([issue here](https://github.com/spring-cloud/spring-cloud-stream/issues/1967)), but you can use native decoding...

```properties
spring.kafka.producer.properties.linger.ms=50

spring.cloud.stream.bindings.input-in-0.consumer.batch-mode=true
spring.cloud.stream.bindings.input-in-0.group=kbgh892
spring.cloud.stream.bindings.input-in-0.destination=kbgh892
spring.cloud.stream.bindings.input-in-0.content-type=text/plain

spring.cloud.stream.bindings.input-in-0.consumer.use-native-decoding=true
spring.cloud.stream.kafka.bindings.input-in-0.consumer.configuration.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
```

```java
@SpringBootApplication
public class Kbgh892Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh892Application.class, args);
	}

	@Bean
	Consumer<List<String>> input() {
		return list -> {
			System.out.println(list);
		};
	}

	@Bean
	public ApplicationRunner runner(KafkaTemplate<byte[], byte[]> template) {
		return args -> {
			template.send("kbgh892", "foo".getBytes());
			template.send("kbgh892", "bar".getBytes());
		};
	}

}
```

**Comment by AlvinYueChao** [comment]
@garyrussell thanks for your demo. it works. I got another way to get the same result is I still use @StreamListener and use ThreadLocal to maintains batch of messages then process them.

**Comment by justlaputa** [comment]
> Bear in mind that batch mode is not supported with `@StreamListener` - it only works with the newer functional programming model.

it's better to mention this in the document

**Comment by sobychacko** [comment]
Docs changes are addressed through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/14c4c4a9059dcc30e7f0ff11ccade3a2cc21362b.

**Comment by Bryce-huang** [comment]
Is this bug fixed?

**Comment by sobychacko** [comment]
@Bryce-huang There was no bug associated with this issue. There was only a docs issue that got addressed through the commit mentioned above.

**Comment by noiseorigin** [comment]
It works with both @StreamListener and the functional programing mode now. I wonder if we still need this line in the docs 

> Bear in mind that batch mode is not supported with @StreamListener - it only works with the newer functional programming model.
