### ISSUE TITLE
Customise objectmapper used by JsonSerde

### ISSUE THREAD

**Issue by ffazil** [spring-cloud/spring-cloud-stream-binder-kafka#933]
I get the below exception when trying to transform a KStream. I tried debugging and introspecting the `objectMapper` inside `JsonSerde` and found that the `jackson money module` is not registered by the object mapper. How do I customise the object mapper used by `JsonSerde` ? Am I moving in the right direction based on the below exception? 

Processing code like 

````
	@StreamListener
    public KStream<UUID, MonetaryAmount> processed(@Input(Bindings.SALES_ORDER_PROCESSED) KStream<UUID, SalesOrderProcessed> orderProcessedStream) {

        KStream<UUID, MonetaryAmount> totalStream = orderProcessedStream
                .peek((key, value) -> {
                    log.info("Key: {} | Value: {}", key, value);
                })
                .map((key, value) -> new KeyValue<>(value.getSaleOrder().getId(), value.getSaleOrder().getTotalPaid()))
                .groupByKey()
                .reduce((a, b) -> a.add(b))
                .toStream();

        return totalStream;

    }
````

and `application.yml` is like

````
spring:
  application:
    name: analytics-service
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      accept-empty-string-as-null-object: true
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: kafka:9092
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
              spring.json.trusted.packages: '*'
              commit.interval.ms: 1000
              auto.offset.reset: earliest
              replication.factor: 3
              client.id: interplay-analytics
              allow.auto.create.topics: true
              ssl.endpoint.identification.algorithm: https
              sasl.mechanism: PLAIN
              request.timeout.ms: 20000
              retry.backoff.ms: 500
              sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="api_key" password="secret";
              security.protocol: SASL_SSL
            replicationFactor: 3
            application-id: dashboard
      bindings:
        sopi:
          destination: application.saleorder.processed
          consumer:
            startOffset: latest
            resetOffsets: true
            autoRebalanceEnabled: false
            useNativeDecoding: false
            valueSerde: org.springframework.kafka.support.serializer.JsonSerde
````

and exception is like

````
Exception in thread "interplay-analytics-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Deserialization exception handler is set to fail upon a deserialization error. If you would rather have the streaming pipeline continue after a deserialization error, please set the default.deserialization.exception.handler appropriately.
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:80)
	at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:175)
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:112)
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:162)
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:765)
	at org.apache.kafka.streams.processor.internals.StreamThread.addRecordsToTasks(StreamThread.java:943)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:764)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
Caused by: org.apache.kafka.common.errors.SerializationException: Can't deserialize data [[123, 34, 99, 117, 114, 114, 101, 110, 99, 121, 34, 58, 123, 34, 99, 111, 110, 116, 101, 120, 116, 34, 58, 123, 34, 101, 109, 112, 116, 121, 34, 58, 102, 97, 108, 115, 101, 44, 34, 112, 114, 111, 118, 105, 100, 101, 114, 78, 97, 109, 101, 34, 58, 34, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 67, 117, 114, 114, 101, 110, 99, 121, 34, 125, 44, 34, 100, 101, 102, 97, 117, 108, 116, 70, 114, 97, 99, 116, 105, 111, 110, 68, 105, 103, 105, 116, 115, 34, 58, 50, 44, 34, 99, 117, 114, 114, 101, 110, 99, 121, 67, 111, 100, 101, 34, 58, 34, 65, 85, 68, 34, 44, 34, 110, 117, 109, 101, 114, 105, 99, 67, 111, 100, 101, 34, 58, 51, 54, 125, 44, 34, 110, 117, 109, 98, 101, 114, 34, 58, 50, 49, 44, 34, 102, 97, 99, 116, 111, 114, 121, 34, 58, 123, 34, 100, 101, 102, 97, 117, 108, 116, 77, 111, 110, 101, 116, 97, 114, 121, 67, 111, 110, 116, 101, 120, 116, 34, 58, 123, 34, 109, 97, 120, 83, 99, 97, 108, 101, 34, 58, 54, 51, 44, 34, 112, 114, 101, 99, 105, 115, 105, 111, 110, 34, 58, 48, 44, 34, 102, 105, 120, 101, 100, 83, 99, 97, 108, 101, 34, 58, 102, 97, 108, 115, 101, 44, 34, 97, 109, 111, 117, 110, 116, 84, 121, 112, 101, 34, 58, 34, 111, 114, 103, 46, 106, 97, 118, 97, 109, 111, 110, 101, 121, 46, 109, 111, 110, 101, 116, 97, 46, 77, 111, 110, 101, 121, 34, 44, 34, 101, 109, 112, 116, 121, 34, 58, 102, 97, 108, 115, 101, 44, 34, 112, 114, 111, 118, 105, 100, 101, 114, 78, 97, 109, 101, 34, 58, 110, 117, 108, 108, 125, 44, 34, 109, 97, 120, 78, 117, 109, 98, 101, 114, 34, 58, 110, 117, 108, 108, 44, 34, 109, 105, 110, 78, 117, 109, 98, 101, 114, 34, 58, 110, 117, 108, 108, 44, 34, 97, 109, 111, 117, 110, 116, 84, 121, 112, 101, 34, 58, 34, 111, 114, 103, 46, 106, 97, 118, 97, 109, 111, 110, 101, 121, 46, 109, 111, 110, 101, 116, 97, 46, 77, 111, 110, 101, 121, 34, 44, 34, 109, 97, 120, 105, 109, 97, 108, 77, 111, 110, 101, 116, 97, 114, 121, 67, 111, 110, 116, 101, 120, 116, 34, 58, 123, 34, 109, 97, 120, 83, 99, 97, 108, 101, 34, 58, 45, 49, 44, 34, 112, 114, 101, 99, 105, 115, 105, 111, 110, 34, 58, 48, 44, 34, 102, 105, 120, 101, 100, 83, 99, 97, 108, 101, 34, 58, 102, 97, 108, 115, 101, 44, 34, 97, 109, 111, 117, 110, 116, 84, 121, 112, 101, 34, 58, 34, 111, 114, 103, 46, 106, 97, 118, 97, 109, 111, 110, 101, 121, 46, 109, 111, 110, 101, 116, 97, 46, 77, 111, 110, 101, 121, 34, 44, 34, 101, 109, 112, 116, 121, 34, 58, 102, 97, 108, 115, 101, 44, 34, 112, 114, 111, 118, 105, 100, 101, 114, 78, 97, 109, 101, 34, 58, 110, 117, 108, 108, 125, 125, 44, 34, 99, 111, 110, 116, 101, 120, 116, 34, 58, 123, 34, 109, 97, 120, 83, 99, 97, 108, 101, 34, 58, 45, 49, 44, 34, 112, 114, 101, 99, 105, 115, 105, 111, 110, 34, 58, 50, 53, 54, 44, 34, 102, 105, 120, 101, 100, 83, 99, 97, 108, 101, 34, 58, 102, 97, 108, 115, 101, 44, 34, 97, 109, 111, 117, 110, 116, 84, 121, 112, 101, 34, 58, 34, 111, 114, 103, 46, 106, 97, 118, 97, 109, 111, 110, 101, 121, 46, 109, 111, 110, 101, 116, 97, 46, 77, 111, 110, 101, 121, 34, 44, 34, 101, 109, 112, 116, 121, 34, 58, 102, 97, 108, 115, 101, 44, 34, 112, 114, 111, 118, 105, 100, 101, 114, 78, 97, 109, 101, 34, 58, 110, 117, 108, 108, 125, 44, 34, 110, 101, 103, 97, 116, 105, 118, 101, 79, 114, 90, 101, 114, 111, 34, 58, 102, 97, 108, 115, 101, 44, 34, 112, 111, 115, 105, 116, 105, 118, 101, 34, 58, 116, 114, 117, 101, 44, 34, 112, 111, 115, 105, 116, 105, 118, 101, 79, 114, 90, 101, 114, 111, 34, 58, 116, 114, 117, 101, 44, 34, 122, 101, 114, 111, 34, 58, 102, 97, 108, 115, 101, 44, 34, 110, 101, 103, 97, 116, 105, 118, 101, 34, 58, 102, 97, 108, 115, 101, 44, 34, 110, 117, 109, 98, 101, 114, 83, 116, 114, 105, 112, 112, 101, 100, 34, 58, 50, 49, 125]] from topic [dashboard-KSTREAM-REDUCE-STATE-STORE-0000000010-repartition]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.javamoney.moneta.Money` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"currency":{"context":{"empty":false,"providerName":"java.util.Currency"},"defaultFractionDigits":2,"currencyCode":"AUD","numericCode":36},"number":21,"factory":{"defaultMonetaryContext":{"maxScale":63,"precision":0,"fixedScale":false,"amountType":"org.javamoney.moneta.Money","empty":false,"providerName":null},"maxNumber":null,"minNumber":null,"amountType":"org.javamoney.moneta.Money","maximalMonetaryContext":{"maxScale":-1,"precision":0,"fixedScale":false,"amountType":"org.javamoney.moneta.Mon"[truncated 288 bytes]; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1611)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2057)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1533)
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:461)
	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:63)
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66)
	at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:175)
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:112)
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:162)
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:765)
	at org.apache.kafka.streams.processor.internals.StreamThread.addRecordsToTasks(StreamThread.java:943)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:764)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
````

I tried defining a bean for the money module and also customising the object mapper. But JsonSerde does not use the primary object mapper bean by `Spring` . And both these approaches does not work. 

````
    @Bean
    public Module moneyModule(){
        return new MoneyModule();
    }
````
and 

````
    @Bean
    public Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder(){
        Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
        builder.modules(new JavaTimeModule(), new MoneyModule(), new ParameterNamesModule(),
                new Jdk8Module());
        return builder;
    }
````

**Comment by sobychacko** [comment]
@ffazil Have you tried creating a custom `Serde` by extending `JsonSerde` and use that instead? In your implementation, you can define the appropriate object mapper. That should work.

**Comment by ffazil** [comment]
That worked. Thanks a ton @sobychacko .
