### ISSUE TITLE
Update Topic configuration from topic.properties on topic provisioning

### ISSUE THREAD

**Issue by nekator** [spring-cloud/spring-cloud-stream-binder-kafka#951]
It seems that topic configuration done via `spring.cloud.stream.kafka.bindings.<binding>.consumer.topic.properties` and
`spring.cloud.stream.kafka.bindings.<binding>.producer.topic.properties` do not update the topic configuration  if the topic already exsists.

It is possible to update a topic configuration via kafka-admin-client like [this](https://stackoverflow.com/a/54026448).

In my opinion it would be a nice feature to modify the topic configuration to fully manage topics from the application.

**Comment by sobychacko** [comment]
@nekator Sounds like a good feature to me. I noticed that you made some changes to the provisioner in your fork. Is that related to this? Do you want to send a PR? We will be happy to review it.

**Comment by nekator** [comment]
I tried to implement this feature and started with topic configuration updates. 
Now I have to handle configuration deletes and this feature might be ready. 

Hopefully my PR will be ready this weekend.

**Comment by sobychacko** [comment]
@nekator Thanks for the quick response. Looking forward to the PR!

**Comment by nekator** [comment]
@sobychacko i could not find any good solution to handle property deletions. Instead of deleting the property i would recommend to change the value back to the default value and later remove the property.

So my PR will only handle new properties or changed properties.

**Comment by sparcs360** [comment]
FYI @nekator, @sobychacko: The `incrementalAlterConfigs` function used [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/859952b32abfe89a25d3f208158dc39e13a90094#diff-f598189b6216fa8c4b0c4e66c7c082b96643fbe6fb5d4c3d1a2482c9052505adR403) is new in Kafka 2.3

I get the following error when running my app with `Hoxton.SR9` and a < v2.3 Broker:
```
o.a.k.c.e.UnsupportedVersionException: The broker does not support INCREMENTAL_ALTER_CONFIGS
Wrapped by: j.u.c.ExecutionException: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support INCREMENTAL_ALTER_CONFIGS
	at o.a.k.c.i.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at o.a.k.c.i.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at o.a.k.c.i.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:104)
	at o.a.k.c.i.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
	at o.s.c.s.b.k.p.KafkaTopicProvisioner.createTopicAndPartitions(KafkaTopicProvisioner.java:404)
	at o.s.c.s.b.k.p.KafkaTopicProvisioner.createTopicIfNecessary(KafkaTopicProvisioner.java:349)
	at o.s.c.s.b.k.p.KafkaTopicProvisioner.createTopic(KafkaTopicProvisioner.java:326)
	... 13 common frames omitted
Wrapped by: o.s.c.s.p.ProvisioningException: Provisioning exception; nested exception is java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support INCREMENTAL_ALTER_CONFIGS
	at o.s.c.s.b.k.p.KafkaTopicProvisioner.createTopic(KafkaTopicProvisioner.java:339)
	at o.s.c.s.b.k.p.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:155)
	at o.s.c.s.b.k.p.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:86)
	at o.s.c.s.b.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:223)
	at o.s.c.s.b.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:91)
	at o.s.c.s.b.AbstractBinder.bindProducer(AbstractBinder.java:152)
	at o.s.c.s.b.BindingService.lambda$rescheduleProducerBinding$4(BindingService.java:336)
	at o.s.s.s.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at j.u.c.Executors$RunnableAdapter.call(Unknown Source)
	at j.u.c.FutureTask.run(Unknown Source)
	... 4 frames truncated
```

Please ignore if this is intentional

**Comment by garyrussell** [comment]
I believe that's a bug; please open a new issue - we don't (as far as I know) require a minimum broker level, and certainly we shouldn't impose that in a point release SR8->SR9. I think a `try/catch` should be added.

**Comment by garyrussell** [comment]
As a work around, you can disable the code by setting `autoCreateTopics` to `false` (after the app has run the first time).

It probably should have gotten its own property `autoAlterTopics` (default false).
