### ISSUE TITLE
Add support for Avro GenericData Record to DLQ ErrorHandler()

### ISSUE THREAD

**Issue by dopeymac** [spring-cloud/spring-cloud-stream-binder-kafka#96]
In the KafkaMessageChannelBinder, the DLQ error handler attempts to cast the message value to a byte array, this may not always work since users may be using the Confluent serialized avro objects.

```
java.lang.ClassCastException: org.apache.avro.generic.GenericData$Record cannot be cast to [B
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$2.handle(KafkaMessageChannelBinder.java:354)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:779)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:707)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.access$2500(KafkaMessageListenerContainer.java:229)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ListenerInvoker.run(KafkaMessageListenerContainer.java:976)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mbogoevici** [comment]
Closing this as #125 will resend the raw payload to the DLQ.
